/**
 * Pinned equity beta pack — regressed betas with their own error bars.
 *
 * Why this exists: `resolveBeta` had three branches — bottom-up from peer
 * betas, an explicit scalar, or a sector prior — and on 33 loaded companies the
 * first almost never clears `MIN_BOTTOM_UP_PEERS`, so beta resolved `prior` for
 * effectively every run. A sector prior is the one input in `ke = rf + beta x
 * ERP` that nothing in the ladder could improve, because no peer set was deep
 * enough to estimate it and no observation was pinned to replace it.
 *
 * A beta regressed against a market index is such an observation: reproducible
 * from public price history, and — unlike a scalar someone typed — it arrives
 * with a standard error that says how much to trust it. That error bar is the
 * point. A beta of 1.43 with se 0.25 and r-squared 0.11 is not a measurement,
 * and this pack is built so that such a name resolves `prior` with a stated
 * reason rather than being laundered into a `sourced` tier.
 *
 * SOURCING RULES FOR WHOEVER REFRESHES THIS
 * 1. Do not hand-edit `indiaEquityBetaPack.ts`. It is generated by
 *    `scripts/refresh-beta-pack.ts`, which fetches the price history and does
 *    the regression, so every number in it is re-derivable by re-running one
 *    command. A hand-typed beta is exactly the unverifiable input this replaces.
 * 2. Every constituent keeps its diagnostics — n, standard error, r-squared,
 *    window. A beta without them cannot be gated, and an ungated beta is a
 *    sector prior wearing a decimal point.
 * 3. `windowEnd` is the last COMPLETED period in the estimation window, not the
 *    date you ran the script. The current bar is still moving; including it
 *    makes the pinned figure depend on the hour it was fetched.
 */

/**
 * How long a regressed beta stays usable.
 *
 * Longer than the 30-day risk-free window in `macroPack.ts` and for a different
 * reason: a G-Sec yield is a level that moves daily, while this is a five-year
 * covariance estimate where one extra month shifts the slope very little. Value
 * Line refreshes quarterly and Damodaran annually; 180 days sits between them,
 * so a pack refreshed twice a year is never silently stale.
 */
export const BETA_STALENESS_DAYS = 180;

/**
 * Minimum return observations. At weekly sampling this is two years — below
 * that the slope is dominated by whatever regime the short window happened to
 * catch. Recently-listed names (LICI at 219 weekly observations, PAYTM at 245)
 * clear this floor while still being visibly shorter than a full five years,
 * which is why `observations` travels with the estimate.
 */
export const MIN_BETA_OBSERVATIONS = 104;

/**
 * Maximum standard error on the slope.
 *
 * Chosen from the observed distribution across the 33 loaded companies (5y
 * weekly against NIFTY 50): median se 0.094, and the closest name above this
 * cut sits at 0.139. So the threshold is not carving through a cluster — it
 * separates 31 names whose betas are measured from 2 whose are not.
 *
 * What it buys, concretely: se 0.15 bounds the 95% confidence interval at
 * roughly +/-0.29 on beta, which at a 7% ERP is +/-2.1pp on the cost of equity.
 * Wider than that and the discount rate's error bar swamps the difference
 * between a beta and a guess, so the honest answer is the stated prior.
 *
 * Deliberately NOT also gating on r-squared. Standard error already carries the
 * precision of the slope, and r-squared is a monotone-related summary of the
 * same fit; gating on both would reject the same names twice while implying two
 * independent checks were passed. r-squared is kept as a diagnostic so a
 * reviewer can see how much of the variance the market actually explains.
 */
export const MAX_BETA_STANDARD_ERROR = 0.15;

/**
 * Plausibility band. Rejects sign and alignment errors — a negative beta on a
 * large-cap Indian equity almost always means the return series and the
 * benchmark were joined wrong — without encoding a view on what beta *should*
 * be. High-beta names genuinely reach 1.4 here, so the ceiling is well above
 * the observed range rather than snug against it.
 */
const PLAUSIBLE_BETA = { min: 0.05, max: 3 } as const;

/** One company's regressed beta and everything needed to judge it. */
export interface EquityBetaObservation {
  /** Exchange ticker, matching `registry.json`'s `ticker` (e.g. "ASIANPAINT"). */
  readonly ticker: string;
  /**
   * OLS slope of the stock's return on the benchmark's return.
   *
   * The raw levered beta as observed, at whatever leverage the company actually
   * carried over the window. Deliberately not relevered to a target D/E: doing
   * that correctly needs the window-average leverage, which this pack does not
   * carry, and an approximate relevering would move the number without
   * improving it. The bottom-up path in `capitalCostAssumptions.ts` is where
   * relevering belongs, because there the peer leverage is known per peer.
   *
   * Also deliberately not Blume-adjusted (the 0.67 x raw + 0.33 x 1 shrinkage
   * Bloomberg reports). That adjustment pulls the estimate toward a prior of 1,
   * which is precisely the thing the provenance tiers exist to keep separable
   * from an observation. A reviewer who wants adjusted betas can shrink these.
   */
  readonly leveredBeta: number;
  /** Standard error of the slope: sqrt((SSE/(n-2)) / var(benchmark)). */
  readonly standardError: number;
  /** Share of the stock's return variance explained by the benchmark. */
  readonly rSquared: number;
  /** Paired return observations behind the regression. */
  readonly observations: number;
  /** First return period in the window (YYYY-MM-DD). */
  readonly windowStart: string;
  /** Last COMPLETED return period in the window (YYYY-MM-DD). */
  readonly windowEnd: string;
}

export interface EquityBetaPack {
  /** Date the pack was assembled (YYYY-MM-DD). */
  readonly asOf: string;
  /** The market index regressed against, named so a reviewer can re-run it. */
  readonly benchmark: string;
  /**
   * Sampling frequency, which is not a detail: the same five years of TCS gives
   * a materially different slope at daily, weekly, and monthly sampling, and
   * for thin names the spread across frequencies is wider than any one
   * frequency's confidence interval. Recording it is what makes the estimate
   * reproducible rather than merely plausible.
   */
  readonly frequency: "daily" | "weekly" | "monthly";
  /** Where the price history came from, at re-fetchable precision. */
  readonly source: string;
  readonly constituents: readonly EquityBetaObservation[];
}

export type EquityBetaStatus =
  | {
      readonly status: "usable";
      readonly ticker: string;
      readonly beta: number;
      readonly standardError: number;
      readonly rSquared: number;
      readonly observations: number;
      /** The window end — the date this estimate is an observation *as of*. */
      readonly asOf: string;
      readonly source: string;
      readonly method: string;
    }
  | {
      readonly status: "unusable";
      readonly ticker: string | null;
      readonly reason: string;
    };

function daysBetween(fromIsoDate: string, toIsoDate: string): number | null {
  const from = Date.parse(fromIsoDate);
  const to = Date.parse(toIsoDate);
  if (!Number.isFinite(from) || !Number.isFinite(to)) return null;
  return Math.round((to - from) / 86_400_000);
}

/**
 * Resolve one company's beta from the pack.
 *
 * `unusable` always carries a reason, for the same purpose it does in
 * `peerPack.ts`: a reviewer has to be able to tell "we had no beta for this
 * name" from "we had one and it was too noisy to use", because those imply
 * different next actions.
 */
export function resolveEquityBeta(
  pack: EquityBetaPack | null | undefined,
  ticker: string | null | undefined,
  options?: {
    readonly analysisAsOf?: string | null;
    readonly maxStandardError?: number;
    readonly minObservations?: number;
  },
): EquityBetaStatus {
  if (!pack) {
    return { status: "unusable", ticker: ticker ?? null, reason: "No pinned equity beta pack supplied; a regressed beta needs pinned price history." };
  }
  const key = ticker?.trim().toUpperCase();
  if (!key) {
    return { status: "unusable", ticker: null, reason: "No ticker on the run, so no beta could be looked up; the pack is keyed by exchange ticker." };
  }

  const observation = pack.constituents.find((item) => item.ticker.trim().toUpperCase() === key);
  if (!observation) {
    return { status: "unusable", ticker: key, reason: `Equity beta pack has no constituent for ${key} (benchmark ${pack.benchmark}).` };
  }

  if (!Number.isFinite(observation.leveredBeta) || !Number.isFinite(observation.standardError)) {
    return { status: "unusable", ticker: key, reason: `${key} beta or standard error is not a finite number.` };
  }
  if (observation.leveredBeta < PLAUSIBLE_BETA.min || observation.leveredBeta > PLAUSIBLE_BETA.max) {
    return {
      status: "unusable",
      ticker: key,
      reason: `${key} beta of ${observation.leveredBeta} is outside the plausible band ${PLAUSIBLE_BETA.min}-${PLAUSIBLE_BETA.max}; the return series and benchmark may be misaligned.`,
    };
  }

  const minObservations = options?.minObservations ?? MIN_BETA_OBSERVATIONS;
  if (observation.observations < minObservations) {
    return {
      status: "unusable",
      ticker: key,
      reason: `${key} beta rests on ${observation.observations} ${pack.frequency} observation(s); at least ${minObservations} are required.`,
    };
  }

  const maxStandardError = options?.maxStandardError ?? MAX_BETA_STANDARD_ERROR;
  if (observation.standardError > maxStandardError) {
    return {
      status: "unusable",
      ticker: key,
      reason: `${key} beta of ${observation.leveredBeta.toFixed(3)} has standard error ${observation.standardError.toFixed(3)} (r-squared ${observation.rSquared.toFixed(3)}), above the ${maxStandardError} limit; the estimate is too imprecise to outrank a stated prior.`,
    };
  }

  if (!Number.isFinite(Date.parse(observation.windowEnd))) {
    return { status: "unusable", ticker: key, reason: `${key} has an invalid window end "${observation.windowEnd}".` };
  }

  const analysisAsOf = options?.analysisAsOf ?? null;
  if (analysisAsOf) {
    const age = daysBetween(observation.windowEnd, analysisAsOf);
    if (age == null) {
      return { status: "unusable", ticker: key, reason: `Cannot compare ${key} window end "${observation.windowEnd}" with analysis date "${analysisAsOf}".` };
    }
    if (age < 0) {
      return {
        status: "unusable",
        ticker: key,
        reason: `${key} beta window ends ${observation.windowEnd}, after the analysis date ${analysisAsOf}; that would be look-ahead.`,
      };
    }
    if (age > BETA_STALENESS_DAYS) {
      return {
        status: "unusable",
        ticker: key,
        reason: `${key} beta window ended ${age} days before the analysis (${observation.windowEnd}); limit is ${BETA_STALENESS_DAYS} days.`,
      };
    }
  }

  return {
    status: "usable",
    ticker: key,
    beta: observation.leveredBeta,
    standardError: observation.standardError,
    rSquared: observation.rSquared,
    observations: observation.observations,
    asOf: observation.windowEnd,
    source: pack.source,
    method: `OLS on ${observation.observations} ${pack.frequency} returns vs ${pack.benchmark}, ${observation.windowStart} to ${observation.windowEnd}; se ${observation.standardError.toFixed(3)}, r-squared ${observation.rSquared.toFixed(3)}`,
  };
}
