// GENERATED by scripts/accountability/run-all.ts on 2026-10-08 — do not edit by hand.
//
// Panel estimates of how fast abnormal operating profitability fades, from
// 23 Indian industrial companies' core-RNOA history (pooled AR(1) of
// the deviation from each year's cross-sectional median; see
// src/engine/accountability/persistence.ts). "all" is the pooled fallback.

export interface PanelPersistencePrior {
  readonly phi: number;
  readonly pairs: number;
  readonly companies: number;
}

export const PERSISTENCE_PRIORS_AS_OF = "2026-10-08";

export const PANEL_PERSISTENCE_PRIORS: Readonly<Record<string, PanelPersistencePrior>> = {
  "all": { phi: 0.9698, pairs: 257, companies: 23 },
  "conglomerate": { phi: 0.9393, pairs: 39, companies: 3 },
  "consumer": { phi: 0.8568, pairs: 67, companies: 7 },
  "cyclical": { phi: 0.3081, pairs: 39, companies: 3 },
  "industrial": { phi: 0.9372, pairs: 38, companies: 3 },
};
