import asianPaintsAuditedFixture from "./__fixtures__/asian-paints-capitaline-audited.json";
import itcAuditedFixture from "./__fixtures__/itc-capitaline-audited.json";
import { processCompanyData } from "./pipeline";
import { evaluateQualityGate } from "./mappingAudit";
import { getAnalysisPolicyVersions } from "./policyVersions";
import { RawPeriodData, DEFAULT_CONFIG, EngineConfig, RecastPeriod } from "./types";
import { resolveValuationReadiness, ValuationReadiness } from "./valuationPolicy";

export interface GoldenCompanyExpectation {
  qualityGateTier: "Tier 1" | "Tier 2" | "Tier 3";
  valuationBlocked: boolean;
  valuationStatus: "production-ready" | "warning" | "guarded";
  minPeriods: number;
  requiredTerminalFlags?: string[];
  forbiddenTerminalFlags?: string[];
  ratioRanges?: Partial<Record<"ROCE" | "RNOA" | "NBC" | "FLEV" | "cash_conversion_ratio", [number, number]>>;
}

export interface GoldenCompanyCase {
  id: string;
  companyId: string;
  source: "audited-run" | "curated-contrast" | "real-company-sample";
  note: string;
  rawData: RawPeriodData[];
  expectation: GoldenCompanyExpectation;
}

export interface GoldenCompanyResult {
  companyId: string;
  source: GoldenCompanyCase["source"];
  periods: RecastPeriod[];
  qualityGate: ReturnType<typeof evaluateQualityGate>;
  valuationReadiness: ValuationReadiness;
  latestPeriod: RecastPeriod;
  policyVersions: ReturnType<typeof getAnalysisPolicyVersions>;
}

const vstRealCompanySample: RawPeriodData[] = [
  {
    company_id: "VST",
    period_end: "2021-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1486,
      "Total Equity__BalanceSheet": 940,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 9,
      "Bank Balances Other Than Cash and Cash Equivalents__BalanceSheet": 11,
      "Current Investments__BalanceSheet": 884,
      "Investments - Long-term__BalanceSheet": 3,
      "Others Financial Assets - Short-term__BalanceSheet": 1,
      "Long Term Borrowings__BalanceSheet": 0,
      "Short Term Borrowings__BalanceSheet": 0,
      "Lease Liabilities__BalanceSheet": 0,
      "Others Financial Liabilities - Long-term__BalanceSheet": 0,
      "Others Financial Liabilities - Short-term__BalanceSheet": 38,
      "Revenue From Operations(Net)__ProfitLoss": 537,
      "Other Income__ProfitLoss": 28,
      "Total Comprehensive Income for the Year__ProfitLoss": 100,
      "Non-Controlling Interests__ProfitLoss": 0,
      "Profit After Tax__ProfitLoss": 97,
      "Finance Cost__ProfitLoss": 0,
      "Tax Expenses__ProfitLoss": 19,
      "Profit Before Tax__ProfitLoss": 116,
      "Net Cash from Operating Activities__CashFlow": 286,
      "Purchased of Fixed Assets__CashFlow": 46,
      "Dividend Paid__CashFlow": 159,
      "Exceptional Items Before Tax__ProfitLoss": -15,
      "Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss__ProfitLoss": 3,
      "Interest Received__CashFlow": 0,
      "Dividend Received__CashFlow": 0,
      "P/L on Sales of Invest__CashFlow": 0,
    },
  },
  {
    company_id: "VST",
    period_end: "2022-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1591,
      "Total Equity__BalanceSheet": 1074,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 4,
      "Bank Balances Other Than Cash and Cash Equivalents__BalanceSheet": 11,
      "Current Investments__BalanceSheet": 768,
      "Investments - Long-term__BalanceSheet": 203,
      "Others Financial Assets - Short-term__BalanceSheet": 3,
      "Long Term Borrowings__BalanceSheet": 0,
      "Short Term Borrowings__BalanceSheet": 0,
      "Lease Liabilities__BalanceSheet": 0,
      "Others Financial Liabilities - Long-term__BalanceSheet": 0,
      "Others Financial Liabilities - Short-term__BalanceSheet": 32,
      "Revenue From Operations(Net)__ProfitLoss": 698,
      "Other Income__ProfitLoss": 26,
      "Total Comprehensive Income for the Year__ProfitLoss": 196,
      "Non-Controlling Interests__ProfitLoss": 0,
      "Profit After Tax__ProfitLoss": 195,
      "Finance Cost__ProfitLoss": 0,
      "Tax Expenses__ProfitLoss": 66,
      "Profit Before Tax__ProfitLoss": 261,
      "Net Cash from Operating Activities__CashFlow": 277,
      "Purchased of Fixed Assets__CashFlow": 49,
      "Dividend Paid__CashFlow": 176,
      "Exceptional Items Before Tax__ProfitLoss": 0,
      "Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss__ProfitLoss": 1,
      "Interest Received__CashFlow": 10,
      "Dividend Received__CashFlow": 0,
      "P/L on Sales of Invest__CashFlow": 0,
    },
  },
  {
    company_id: "VST",
    period_end: "2023-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1654,
      "Total Equity__BalanceSheet": 1180,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 9,
      "Bank Balances Other Than Cash and Cash Equivalents__BalanceSheet": 11,
      "Current Investments__BalanceSheet": 376,
      "Investments - Long-term__BalanceSheet": 202,
      "Others Financial Assets - Short-term__BalanceSheet": 3,
      "Long Term Borrowings__BalanceSheet": 0,
      "Short Term Borrowings__BalanceSheet": 0,
      "Lease Liabilities__BalanceSheet": 0,
      "Others Financial Liabilities - Long-term__BalanceSheet": 0,
      "Others Financial Liabilities - Short-term__BalanceSheet": 42,
      "Revenue From Operations(Net)__ProfitLoss": 709,
      "Other Income__ProfitLoss": 33,
      "Total Comprehensive Income for the Year__ProfitLoss": 196,
      "Non-Controlling Interests__ProfitLoss": 0,
      "Profit After Tax__ProfitLoss": 167,
      "Finance Cost__ProfitLoss": 0,
      "Tax Expenses__ProfitLoss": 71,
      "Profit Before Tax__ProfitLoss": 238,
      "Net Cash from Operating Activities__CashFlow": 181,
      "Purchased of Fixed Assets__CashFlow": 404,
      "Dividend Paid__CashFlow": 215,
      "Exceptional Items Before Tax__ProfitLoss": 0,
      "Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss__ProfitLoss": 0,
      "Interest Received__CashFlow": 17,
      "Dividend Received__CashFlow": 0,
      "P/L on Sales of Invest__CashFlow": 0,
    },
  },
  {
    company_id: "VST",
    period_end: "2024-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1720,
      "Total Equity__BalanceSheet": 1252,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 24,
      "Bank Balances Other Than Cash and Cash Equivalents__BalanceSheet": 11,
      "Current Investments__BalanceSheet": 247,
      "Investments - Long-term__BalanceSheet": 200,
      "Others Financial Assets - Short-term__BalanceSheet": 3,
      "Long Term Borrowings__BalanceSheet": 0,
      "Short Term Borrowings__BalanceSheet": 0,
      "Lease Liabilities__BalanceSheet": 0,
      "Others Financial Liabilities - Long-term__BalanceSheet": 0,
      "Others Financial Liabilities - Short-term__BalanceSheet": 48,
      "Revenue From Operations(Net)__ProfitLoss": 1258,
      "Other Income__ProfitLoss": 34,
      "Total Comprehensive Income for the Year__ProfitLoss": 754,
      "Non-Controlling Interests__ProfitLoss": 0,
      "Profit After Tax__ProfitLoss": 753,
      "Finance Cost__ProfitLoss": 0,
      "Tax Expenses__ProfitLoss": 165,
      "Profit Before Tax__ProfitLoss": 919,
      "Net Cash from Operating Activities__CashFlow": 167,
      "Purchased of Fixed Assets__CashFlow": 94,
      "Dividend Paid__CashFlow": 231,
      "Exceptional Items Before Tax__ProfitLoss": 504,
      "Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss__ProfitLoss": 1,
      "Interest Received__CashFlow": 13,
      "Dividend Received__CashFlow": 0,
      "P/L on Sales of Invest__CashFlow": 0,
    },
  },
  {
    company_id: "VST",
    period_end: "2025-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1816,
      "Total Equity__BalanceSheet": 1323,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 6,
      "Bank Balances Other Than Cash and Cash Equivalents__BalanceSheet": 11,
      "Current Investments__BalanceSheet": 332,
      "Investments - Long-term__BalanceSheet": 199,
      "Others Financial Assets - Short-term__BalanceSheet": 3,
      "Long Term Borrowings__BalanceSheet": 0,
      "Short Term Borrowings__BalanceSheet": 0,
      "Lease Liabilities__BalanceSheet": 0,
      "Others Financial Liabilities - Long-term__BalanceSheet": 0,
      "Others Financial Liabilities - Short-term__BalanceSheet": 50,
      "Revenue From Operations(Net)__ProfitLoss": 2883,
      "Other Income__ProfitLoss": 29,
      "Total Comprehensive Income for the Year__ProfitLoss": 1110,
      "Non-Controlling Interests__ProfitLoss": 0,
      "Profit After Tax__ProfitLoss": 1112,
      "Finance Cost__ProfitLoss": 0,
      "Tax Expenses__ProfitLoss": 363,
      "Profit Before Tax__ProfitLoss": 1475,
      "Net Cash from Operating Activities__CashFlow": 193,
      "Purchased of Fixed Assets__CashFlow": 41,
      "Dividend Paid__CashFlow": 231,
      "Exceptional Items Before Tax__ProfitLoss": -90,
      "Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss__ProfitLoss": -3,
      "Interest Received__CashFlow": 15,
      "Dividend Received__CashFlow": 0,
      "P/L on Sales of Invest__CashFlow": 0,
    },
  },
];

const netCashCompounder: RawPeriodData[] = [
  {
    company_id: "NETCASH_CONSUMER",
    period_end: "2023-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1600,
      "Total Stockholders' Equity__BalanceSheet": 1120,
      "Total Equity__BalanceSheet": 1120,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 260,
      "Current Investments__BalanceSheet": 180,
      "Trade Receivables__BalanceSheet": 120,
      "Inventories__BalanceSheet": 130,
      "Trade Payables__BalanceSheet": 110,
      "Total Current Liabilities__BalanceSheet": 260,
      "Property, Plant and Equipment__BalanceSheet": 420,
      "Long Term Borrowings__BalanceSheet": 30,
      "Short Term Borrowings__BalanceSheet": 10,
      "Others Financial Liabilities - Short-term__BalanceSheet": 15,
      "Revenue From Operations(Net)__ProfitLoss": 1450,
      "Profit Before Tax__ProfitLoss": 255,
      "Tax Expenses__ProfitLoss": 64,
      "Profit After Tax__ProfitLoss": 191,
      "Total Comprehensive Income for the Year__ProfitLoss": 193,
      "Finance Cost__ProfitLoss": 4,
      "Interest Income__ProfitLoss": 15,
      "Other Income__ProfitLoss": 10,
      "Cost of Material Consumed__ProfitLoss": 520,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 145,
      "Other Expenses__ProfitLoss": 300,
      "Depreciation and Amortization__ProfitLoss": 52,
      "Net Cash from Operating Activities__CashFlow": 255,
      "Purchased of Fixed Assets__CashFlow": -70,
      "Dividend Paid__CashFlow": -65,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 12,
      "Dividend Received__CashFlow": 1,
      "Purchase of Investments__CashFlow": -60,
      "Sale of Investments__CashFlow": 40,
    },
  },
  {
    company_id: "NETCASH_CONSUMER",
    period_end: "2024-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1730,
      "Total Stockholders' Equity__BalanceSheet": 1230,
      "Total Equity__BalanceSheet": 1230,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 305,
      "Current Investments__BalanceSheet": 205,
      "Trade Receivables__BalanceSheet": 132,
      "Inventories__BalanceSheet": 138,
      "Trade Payables__BalanceSheet": 118,
      "Total Current Liabilities__BalanceSheet": 278,
      "Property, Plant and Equipment__BalanceSheet": 455,
      "Long Term Borrowings__BalanceSheet": 28,
      "Short Term Borrowings__BalanceSheet": 9,
      "Others Financial Liabilities - Short-term__BalanceSheet": 14,
      "Revenue From Operations(Net)__ProfitLoss": 1580,
      "Profit Before Tax__ProfitLoss": 287,
      "Tax Expenses__ProfitLoss": 72,
      "Profit After Tax__ProfitLoss": 215,
      "Total Comprehensive Income for the Year__ProfitLoss": 217,
      "Finance Cost__ProfitLoss": 4,
      "Interest Income__ProfitLoss": 17,
      "Other Income__ProfitLoss": 11,
      "Cost of Material Consumed__ProfitLoss": 555,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 156,
      "Other Expenses__ProfitLoss": 327,
      "Depreciation and Amortization__ProfitLoss": 56,
      "Net Cash from Operating Activities__CashFlow": 281,
      "Purchased of Fixed Assets__CashFlow": -78,
      "Dividend Paid__CashFlow": -72,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 14,
      "Dividend Received__CashFlow": 1,
      "Purchase of Investments__CashFlow": -66,
      "Sale of Investments__CashFlow": 52,
    },
  },
  {
    company_id: "NETCASH_CONSUMER",
    period_end: "2025-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1875,
      "Total Stockholders' Equity__BalanceSheet": 1345,
      "Total Equity__BalanceSheet": 1345,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 338,
      "Current Investments__BalanceSheet": 228,
      "Trade Receivables__BalanceSheet": 145,
      "Inventories__BalanceSheet": 146,
      "Trade Payables__BalanceSheet": 125,
      "Total Current Liabilities__BalanceSheet": 296,
      "Property, Plant and Equipment__BalanceSheet": 492,
      "Long Term Borrowings__BalanceSheet": 24,
      "Short Term Borrowings__BalanceSheet": 8,
      "Others Financial Liabilities - Short-term__BalanceSheet": 13,
      "Revenue From Operations(Net)__ProfitLoss": 1715,
      "Profit Before Tax__ProfitLoss": 319,
      "Tax Expenses__ProfitLoss": 80,
      "Profit After Tax__ProfitLoss": 239,
      "Total Comprehensive Income for the Year__ProfitLoss": 242,
      "Finance Cost__ProfitLoss": 4,
      "Interest Income__ProfitLoss": 19,
      "Other Income__ProfitLoss": 12,
      "Cost of Material Consumed__ProfitLoss": 600,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 168,
      "Other Expenses__ProfitLoss": 351,
      "Depreciation and Amortization__ProfitLoss": 60,
      "Net Cash from Operating Activities__CashFlow": 308,
      "Purchased of Fixed Assets__CashFlow": -82,
      "Dividend Paid__CashFlow": -81,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 15,
      "Dividend Received__CashFlow": 1,
      "Purchase of Investments__CashFlow": -70,
      "Sale of Investments__CashFlow": 58,
    },
  },
];

const leveragedIndustrial: RawPeriodData[] = [
  {
    company_id: "LEVERAGED_INDUSTRIAL",
    period_end: "2023-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 2200,
      "Total Stockholders' Equity__BalanceSheet": 780,
      "Total Equity__BalanceSheet": 780,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 85,
      "Current Investments__BalanceSheet": 10,
      "Trade Receivables__BalanceSheet": 260,
      "Inventories__BalanceSheet": 340,
      "Trade Payables__BalanceSheet": 295,
      "Total Current Liabilities__BalanceSheet": 580,
      "Property, Plant and Equipment__BalanceSheet": 980,
      "Long Term Borrowings__BalanceSheet": 620,
      "Short Term Borrowings__BalanceSheet": 160,
      "Others Financial Liabilities - Short-term__BalanceSheet": 65,
      "Revenue From Operations(Net)__ProfitLoss": 2050,
      "Profit Before Tax__ProfitLoss": 172,
      "Tax Expenses__ProfitLoss": 44,
      "Profit After Tax__ProfitLoss": 128,
      "Total Comprehensive Income for the Year__ProfitLoss": 129,
      "Finance Cost__ProfitLoss": 74,
      "Interest Income__ProfitLoss": 2,
      "Other Income__ProfitLoss": 15,
      "Cost of Material Consumed__ProfitLoss": 1030,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 230,
      "Other Expenses__ProfitLoss": 470,
      "Depreciation and Amortization__ProfitLoss": 88,
      "Net Cash from Operating Activities__CashFlow": 240,
      "Purchased of Fixed Assets__CashFlow": -145,
      "Dividend Paid__CashFlow": -28,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Proceed from Other Long Term Borrowings__CashFlow": 70,
      "Of the Long Term Borrowings__CashFlow": -55,
      "Interest Received__CashFlow": 3,
      "Purchase of Investments__CashFlow": -5,
      "Sale of Investments__CashFlow": 2,
    },
  },
  {
    company_id: "LEVERAGED_INDUSTRIAL",
    period_end: "2024-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 2335,
      "Total Stockholders' Equity__BalanceSheet": 842,
      "Total Equity__BalanceSheet": 842,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 92,
      "Current Investments__BalanceSheet": 12,
      "Trade Receivables__BalanceSheet": 278,
      "Inventories__BalanceSheet": 352,
      "Trade Payables__BalanceSheet": 307,
      "Total Current Liabilities__BalanceSheet": 604,
      "Property, Plant and Equipment__BalanceSheet": 1035,
      "Long Term Borrowings__BalanceSheet": 640,
      "Short Term Borrowings__BalanceSheet": 148,
      "Others Financial Liabilities - Short-term__BalanceSheet": 61,
      "Revenue From Operations(Net)__ProfitLoss": 2190,
      "Profit Before Tax__ProfitLoss": 186,
      "Tax Expenses__ProfitLoss": 47,
      "Profit After Tax__ProfitLoss": 139,
      "Total Comprehensive Income for the Year__ProfitLoss": 141,
      "Finance Cost__ProfitLoss": 72,
      "Interest Income__ProfitLoss": 2,
      "Other Income__ProfitLoss": 16,
      "Cost of Material Consumed__ProfitLoss": 1095,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 244,
      "Other Expenses__ProfitLoss": 492,
      "Depreciation and Amortization__ProfitLoss": 92,
      "Net Cash from Operating Activities__CashFlow": 258,
      "Purchased of Fixed Assets__CashFlow": -154,
      "Dividend Paid__CashFlow": -31,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Proceed from Other Long Term Borrowings__CashFlow": 62,
      "Of the Long Term Borrowings__CashFlow": -59,
      "Interest Received__CashFlow": 3,
      "Purchase of Investments__CashFlow": -6,
      "Sale of Investments__CashFlow": 3,
    },
  },
  {
    company_id: "LEVERAGED_INDUSTRIAL",
    period_end: "2025-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 2475,
      "Total Stockholders' Equity__BalanceSheet": 915,
      "Total Equity__BalanceSheet": 915,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 96,
      "Current Investments__BalanceSheet": 14,
      "Trade Receivables__BalanceSheet": 292,
      "Inventories__BalanceSheet": 366,
      "Trade Payables__BalanceSheet": 318,
      "Total Current Liabilities__BalanceSheet": 625,
      "Property, Plant and Equipment__BalanceSheet": 1090,
      "Long Term Borrowings__BalanceSheet": 655,
      "Short Term Borrowings__BalanceSheet": 142,
      "Others Financial Liabilities - Short-term__BalanceSheet": 58,
      "Revenue From Operations(Net)__ProfitLoss": 2350,
      "Profit Before Tax__ProfitLoss": 205,
      "Tax Expenses__ProfitLoss": 52,
      "Profit After Tax__ProfitLoss": 153,
      "Total Comprehensive Income for the Year__ProfitLoss": 154,
      "Finance Cost__ProfitLoss": 71,
      "Interest Income__ProfitLoss": 2,
      "Other Income__ProfitLoss": 17,
      "Cost of Material Consumed__ProfitLoss": 1165,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 258,
      "Other Expenses__ProfitLoss": 520,
      "Depreciation and Amortization__ProfitLoss": 97,
      "Net Cash from Operating Activities__CashFlow": 278,
      "Purchased of Fixed Assets__CashFlow": -166,
      "Dividend Paid__CashFlow": -33,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Proceed from Other Long Term Borrowings__CashFlow": 58,
      "Of the Long Term Borrowings__CashFlow": -63,
      "Interest Received__CashFlow": 3,
      "Purchase of Investments__CashFlow": -7,
      "Sale of Investments__CashFlow": 3,
    },
  },
];

const exceptionalEventIssuer: RawPeriodData[] = [
  {
    company_id: "EXCEPTIONAL_EVENT_CO",
    period_end: "2023-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1800,
      "Total Stockholders' Equity__BalanceSheet": 860,
      "Total Equity__BalanceSheet": 860,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 120,
      "Current Investments__BalanceSheet": 40,
      "Trade Receivables__BalanceSheet": 175,
      "Inventories__BalanceSheet": 210,
      "Trade Payables__BalanceSheet": 160,
      "Total Current Liabilities__BalanceSheet": 355,
      "Property, Plant and Equipment__BalanceSheet": 690,
      "Long Term Borrowings__BalanceSheet": 210,
      "Short Term Borrowings__BalanceSheet": 58,
      "Others Financial Liabilities - Short-term__BalanceSheet": 25,
      "Revenue From Operations(Net)__ProfitLoss": 1680,
      "Profit Before Tax__ProfitLoss": 202,
      "Tax Expenses__ProfitLoss": 51,
      "Profit After Tax__ProfitLoss": 151,
      "Total Comprehensive Income for the Year__ProfitLoss": 152,
      "Finance Cost__ProfitLoss": 21,
      "Interest Income__ProfitLoss": 4,
      "Other Income__ProfitLoss": 9,
      "Cost of Material Consumed__ProfitLoss": 770,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 212,
      "Other Expenses__ProfitLoss": 383,
      "Depreciation and Amortization__ProfitLoss": 67,
      "Net Cash from Operating Activities__CashFlow": 230,
      "Purchased of Fixed Assets__CashFlow": -118,
      "Dividend Paid__CashFlow": -36,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 4,
      "Purchase of Investments__CashFlow": -14,
      "Sale of Investments__CashFlow": 8,
    },
  },
  {
    company_id: "EXCEPTIONAL_EVENT_CO",
    period_end: "2024-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1925,
      "Total Stockholders' Equity__BalanceSheet": 938,
      "Total Equity__BalanceSheet": 938,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 128,
      "Current Investments__BalanceSheet": 46,
      "Trade Receivables__BalanceSheet": 181,
      "Inventories__BalanceSheet": 218,
      "Trade Payables__BalanceSheet": 168,
      "Total Current Liabilities__BalanceSheet": 369,
      "Property, Plant and Equipment__BalanceSheet": 720,
      "Long Term Borrowings__BalanceSheet": 202,
      "Short Term Borrowings__BalanceSheet": 56,
      "Others Financial Liabilities - Short-term__BalanceSheet": 24,
      "Revenue From Operations(Net)__ProfitLoss": 1765,
      "Profit Before Tax__ProfitLoss": 221,
      "Tax Expenses__ProfitLoss": 56,
      "Profit After Tax__ProfitLoss": 165,
      "Total Comprehensive Income for the Year__ProfitLoss": 166,
      "Finance Cost__ProfitLoss": 20,
      "Interest Income__ProfitLoss": 5,
      "Other Income__ProfitLoss": 10,
      "Cost of Material Consumed__ProfitLoss": 804,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 220,
      "Other Expenses__ProfitLoss": 401,
      "Depreciation and Amortization__ProfitLoss": 70,
      "Net Cash from Operating Activities__CashFlow": 246,
      "Purchased of Fixed Assets__CashFlow": -126,
      "Dividend Paid__CashFlow": -40,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 4,
      "Purchase of Investments__CashFlow": -16,
      "Sale of Investments__CashFlow": 9,
    },
  },
  {
    company_id: "EXCEPTIONAL_EVENT_CO",
    period_end: "2025-03-31",
    raw_metric_values: {
      "Total Assets__BalanceSheet": 1660,
      "Total Stockholders' Equity__BalanceSheet": 640,
      "Total Equity__BalanceSheet": 640,
      "Minority Interest__BalanceSheet": 0,
      "Cash and Cash Equivalents__BalanceSheet": 118,
      "Current Investments__BalanceSheet": 38,
      "Trade Receivables__BalanceSheet": 150,
      "Inventories__BalanceSheet": 170,
      "Trade Payables__BalanceSheet": 120,
      "Total Current Liabilities__BalanceSheet": 300,
      "Property, Plant and Equipment__BalanceSheet": 410,
      "Long Term Borrowings__BalanceSheet": 175,
      "Short Term Borrowings__BalanceSheet": 52,
      "Others Financial Liabilities - Short-term__BalanceSheet": 21,
      "Revenue From Operations(Net)__ProfitLoss": 1820,
      "Profit Before Tax__ProfitLoss": 402,
      "Tax Expenses__ProfitLoss": 94,
      "Profit After Tax__ProfitLoss": 308,
      "Total Comprehensive Income for the Year__ProfitLoss": 520,
      "Finance Cost__ProfitLoss": 19,
      "Interest Income__ProfitLoss": 5,
      "Other Income__ProfitLoss": 14,
      "Exceptional Items Before Tax__ProfitLoss": 180,
      "Profit / (Loss) from Discontinuing Operations__ProfitLoss": 150,
      "Tax Expense of Discontinuing Operations__ProfitLoss": -32,
      "Cost of Material Consumed__ProfitLoss": 782,
      "Employee Benefits / Salaries & other Staff Cost__ProfitLoss": 218,
      "Other Expenses__ProfitLoss": 409,
      "Depreciation and Amortization__ProfitLoss": 68,
      "Net Cash from Operating Activities__CashFlow": 260,
      "Purchased of Fixed Assets__CashFlow": -88,
      "Dividend Paid__CashFlow": -42,
      "Proceeds from Issue of shares (incl share premium)__CashFlow": 0,
      "Interest Received__CashFlow": 4,
      "Purchase of Investments__CashFlow": -11,
      "Sale of Investments__CashFlow": 6,
    },
  },
];

export const GOLDEN_COMPANY_CASES: GoldenCompanyCase[] = [
  {
    id: "itc-audited-run",
    companyId: "ITC",
    source: "audited-run",
    note: "Real audited production run captured from Vercel on 2026-03-29.",
    rawData: (itcAuditedFixture as { rawData: RawPeriodData[] }).rawData,
    expectation: {
      qualityGateTier: "Tier 1",
      valuationBlocked: true,
      valuationStatus: "guarded",
      minPeriods: 15,
      requiredTerminalFlags: [
        "STRUCTURAL_EVENT",
        "PM_OUTLIER_CRITICAL",
        "ROCE_OUTLIER_CRITICAL",
        "RNOA_OUTLIER_CRITICAL",
      ],
      ratioRanges: {
        ROCE: [0.4, 0.6],
        RNOA: [0.8, 1.0],
        NBC: [0.02, 0.05],
      },
    },
  },
  {
    id: "asian-paints-audited-run",
    companyId: "ASIAN PAINTS",
    source: "audited-run",
    note: "Real audited Capitaline run for a clean supported industrial issuer with complete artifact capture.",
    rawData: asianPaintsAuditedFixture.rawData as RawPeriodData[],
    expectation: {
      qualityGateTier: "Tier 1",
      valuationBlocked: false,
      valuationStatus: "production-ready",
      minPeriods: 10,
      forbiddenTerminalFlags: ["STRUCTURAL_EVENT", "CAPITAL_TRANSACTION_LIKELY"],
      ratioRanges: {
        ROCE: [0.12, 0.6],
        RNOA: [0.12, 0.5],
      },
    },
  },
  {
    id: "vst-real-company-sample",
    companyId: "VST",
    source: "real-company-sample",
    note: "Real-company sample embedded in the product and normalized into audited-suite shape.",
    rawData: vstRealCompanySample,
    expectation: {
      qualityGateTier: "Tier 2",
      valuationBlocked: true,
      valuationStatus: "guarded",
      minPeriods: 5,
      ratioRanges: {
        ROCE: [0.2, 1.5],
        FLEV: [-1.1, 0.05],
      },
    },
  },
  {
    id: "netcash-consumer",
    companyId: "NETCASH_CONSUMER",
    source: "curated-contrast",
    note: "Clean net-cash compounder with stable economics.",
    rawData: netCashCompounder,
    expectation: {
      qualityGateTier: "Tier 2",
      valuationBlocked: false,
      valuationStatus: "production-ready",
      minPeriods: 3,
      forbiddenTerminalFlags: ["STRUCTURAL_EVENT", "CAPITAL_TRANSACTION_LIKELY"],
      ratioRanges: {
        ROCE: [0.12, 0.3],
        RNOA: [0.18, 0.35],
        FLEV: [-1.0, 0.05],
      },
    },
  },
  {
    id: "leveraged-industrial",
    companyId: "LEVERAGED_INDUSTRIAL",
    source: "curated-contrast",
    note: "Debt-funded industrial with healthy but leveraged operating structure.",
    rawData: leveragedIndustrial,
    expectation: {
      qualityGateTier: "Tier 1",
      valuationBlocked: false,
      valuationStatus: "warning",
      minPeriods: 3,
      forbiddenTerminalFlags: ["STRUCTURAL_EVENT"],
      ratioRanges: {
        ROCE: [0.12, 0.3],
        RNOA: [0.08, 0.25],
        FLEV: [0.3, 1.5],
      },
    },
  },
  {
    id: "exceptional-event-issuer",
    companyId: "EXCEPTIONAL_EVENT_CO",
    source: "curated-contrast",
    note: "Issuer with a structurally contaminated latest year driven by exceptional and discontinued items.",
    rawData: exceptionalEventIssuer,
    expectation: {
      qualityGateTier: "Tier 2",
      valuationBlocked: true,
      valuationStatus: "guarded",
      minPeriods: 3,
      requiredTerminalFlags: ["STRUCTURAL_EVENT"],
      ratioRanges: {
        ROCE: [0.2, 0.8],
        NBC: [0, 0.2],
      },
    },
  },
];

export function runGoldenCompanyCase(testCase: GoldenCompanyCase, config: EngineConfig = DEFAULT_CONFIG): GoldenCompanyResult {
  const periods = processCompanyData(testCase.rawData, config);
  const qualityGate = evaluateQualityGate(testCase.rawData, null, periods);
  const valuationReadiness = resolveValuationReadiness(periods);
  const latestPeriod = periods[periods.length - 1];

  return {
    companyId: testCase.companyId,
    source: testCase.source,
    periods,
    qualityGate,
    valuationReadiness,
    latestPeriod,
    policyVersions: getAnalysisPolicyVersions(),
  };
}
