export const CapitalineMappingSpec = {
  balanceSheet: {
    totalAssets: ["Total Assets"],
    totalStockholdersEquity: ["Total Stockholders' Equity"],
    totalEquity: ["Total Equity"],
    minorityInterest: ["Minority Interest"],
    financialAssets: {
      cashAndBank: [
        "Cash and Cash Equivalents",
        "Bank Balances Other Than Cash and Cash Equivalents",
        "Earmarked Balances with Bank",
        "Margin Money Balances",
      ],
      currentInvestments: [
        "Current Investments",
        "Investments Carried at Fair Value Through Profit Or Loss (FVTPL)",
        "Investments Carried at Fair Value Through Other Comprehensive Income(FVTOCI)",
        "Investments Carried at Amortized Cost",
      ],
      longTermInvestments: [
        "Investments - Long-term",
        "Non-current Investments",
      ],
      depositsAndRestricted: [
        "Investment in Fixed Deposits",
        "Investment in Certificate of Deposits",
        "Investment in Certificate of Deposits with Scheduled Banks",
        "Restricted Cash",
        "Restricted Deposits",
      ],
      otherFinancialAssets: [
        "Others Financial Assets - Long-term",
        "Others Financial Assets - Short-term",
        "Total Interest Receivable",
        "Interest Receivable",
        "Dividend Receivable",
        "Derivative Receivables / Forward Contract Receivable",
      ],
    },
    dtl: ["Deferred Tax Liabilities (Net)", "Deferred Tax Liability"],
    goodwill: ["Goodwill", "Goodwill - Net"],
    currentAssets: ["Total Current Assets"],
    currentLiabilities: ["Total Current Liabilities"],
    inventoryTop: ["Total Inventory", "Inventories"],
    inventoryComponents: [
      "Raw Materials and Components",
      "Work-in-Progress",
      "Work-in-progress",
      "Finished Goods",
      "Finished Goods / Traded Goods",
      "Stock-in-trade",
      "Stores and Spares",
      "Packing Materials",
      "Goods in Transit",
    ],
    tradeReceivables: ["Trade Receivables", "Total Trade Receivables", "Total Trade Debtors"],
    tradePayables: ["Trade Payables", "Sundry Creditors"],
    ppe: [
      "Net Property, plant and equipment",
      "Total Net Property, plant and equipment (not under Lease)",
      "Property, Plant and Equipment",
      "Fixed Assets",
    ],
    financialObligations: [
      "Long Term Borrowings",
      "Short Term Borrowings",
      "Lease Liabilities",
      "Others Financial Liabilities - Long-term",
      "Others Financial Liabilities - Short-term",
      "Hybrid Perpetual Securities",
    ],
    olComponents: {
      tradePayables: ["Trade Payables", "Sundry Creditors"],
      otherCurrentLiabilities: ["Other Current Liabilities"],
      provisionsCurrent: ["Provisions"],
      provisionsLongTerm: ["Long-term Provisions"],
      currentTaxLiabilities: ["Current Tax Liabilities - Short-term"],
      nonCurrentTaxLiabilities: ["Non Current Tax Liabilities - Long-term"],
      deferredTaxLiabilitiesNet: ["Deferred Tax Liabilities (Net)"],
      otherNonCurrentLiabilities: ["Other Non-Current Liabilities"],
    },
  },
  profitLoss: {
    sales: [
      "Revenue From Operations(Net)",
      "Revenue From Operations",
      "Total Revenue from Operations",
      "Total Revenue",
      "Net Revenue from Operations",
      "Income from Operations",
      "Revenue from Sale of Products",
    ],
    taxExpense: ["Tax Expenses"],
    pbt: ["Profit Before Tax"],
    pat: [
      "Profit After Tax",
      "Profit/(Loss) for the period from Continuing Operations",
      "Profit Attributable to Shareholders",
    ],
    ociNotReclass: ["Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss"],
    ociReclass: ["Other Comprehensive Income That Will Be Reclassified to Profit Or Loss", "Other Comprehensive Income That Will Be Reclassified to Profit Or Loss :"],
    ociUnspecified: ["Other Comprehensive Income no Specification", "Other Comprehensive Income no Specification :"],
    tciGroup: ["Total Comprehensive Income for the Year"],
    tciNci: ["Non-Controlling Interests"],
    preferredDividend: ["Preference Dividend"],
    financeCostTop: ["Finance Cost", "Total Interest Expenses", "Finance Costs", "Interest and Finance Charges"],
    financeIncomeDirect: [
      "Interest Income",
      "Finance Income",
      "Investment Income",
    ],
    otherIncome: ["Other Income"],
    financeCostGranular: [
      "Interest",
      "Interest on Bank Borrowings",
      "Interest on Bonds and Debentures",
      "Interest on Commercial Paper",
      "Interest on Deposits",
      "Interest on External Commercial Borrowings",
      "Interest on Finance Lease",
      "Interest on Foreign Currency Loans",
      "Interest on Other Borrowings",
      "Interest on Other Loans",
      "Interest on Term / Fixed Loans",
      "Interest on Working Capital Loans",
      "Interest - Related Parties",
      "Interest and Finance Charges on Financial Liabilities",
      "Financial Charges on Financial Liabilities at Amortised Cost",
      "Bill Discounting Charges",
      "Amotisation of Borrowing Costs",
      "Other Borrowing Costs",
      "Redemption Premium",
      "Other Interest Expenses",
    ],
    exceptionalItems: ["Exceptional Items Before Tax"],
    extraordinaryItems: ["Extraordinary Items Before Tax"],
    discontinuedItems: [
      "Profit / (Loss) from Discontinuing Operations",
      "Discontinued Operations",
    ],
    cogsMaterial: ["Cost of Material Consumed", "Cost of Materials Consumed", "Consumption of Raw Materials"],
    cogsPurchases: ["Purchases of Stock-in-Trade", "Purchase of Stock-in-Trade", "Purchase of Traded Goods", "Purchase of Finished Goods"],
    cogsInventoryChange: [
      "Changes in Inventories of Finished Goods, Work-in-Progress and Stock-in-Trade",
      "Changes in Inventories",
      "Change in Inventory of Finished Goods, Work-in-Progress and Stock-in-Trade",
    ],
    totalExpenses: ["Total Expenses"],
    employeeExpense: ["Employee Benefits / Salaries & other Staff Cost", "Employee Benefit Expenses", "Employee Benefits Expense", "Employee Cost"],
    otherExpenses: ["Other Expenses", "Other Operating Expenses", "Operating and Other Expenses"],
    depreciationAmortization: [
      "Depreciation and Amortization",
      "Depreciation on Tangible Assets",
      "Depreciation for the current year",
      "Depreciation and Amortisation Expense",
      "Depreciation / Amortisation",
    ],
    sgaAds: [
      "Advertisement, Marketing and Business Development",
      "Advertisements",
      "Advertisement and Sales Promotion",
      "Sales Promotion Expenses",
      "Business Promotion Expenses",
      "Selling and Distribution Expenses",
      "Sales and Distribution Expenses",
    ],
    sgaLegal: [
      "Legal and Professional Fees",
      "Professional Fees",
      "Legal Expenses",
      "Consultancy Charges",
      "Auditors Remuneration",
    ],
    sgaRent: ["Rent", "Rent, rates & Taxes", "Lease Rent / Hire Charges Paid", "Rates and Taxes", "Lease Rentals"],
    sgaFreight: [
      "Freight Outwards and Forwarding Expenses",
      "Transportation",
      "Freight and Forwarding",
      "Packing and Forwarding",
      "Clearing and Forwarding",
      "Commission on Sales",
    ],
    sgaRepairs: [
      "Repairs and Maintenance",
      "Repairs to Building",
      "Repairs to Machinery",
      "Repairs to Other Assets",
      "Maintenance Expenses",
      "Travelling and Conveyance",
      "CSR Expenditure",
      "Royalty",
    ],
    sgaPower: ["Power, Fuel and Water", "Power, Oil & Fuel", "Fuel and Power", "Power and Fuel"],
    retainedEarningsProxy: [
      "Unappropriated Profits Carried Forward",
      "Unappropriated Profits Brought Forward",
      "Other Equity",
      "Profit and Loss Account Closing Balance",
    ],
    otherItemsAliases: [
      "Share of profit/loss of associates",
      "Share of profit / (loss) of associates",
      "Share of Loss in Partnership Firm",
      "Equity accounted income",
      "Share of profit/(loss) in associate companies / joint ventures",
    ],
  },
  cashFlow: {
    cfo: ["Net Cash from Operating Activities"],
    capex: [
      "Purchased of Fixed Assets",
      "Purchase of Fixed Assets",
      "Capital Expenditure",
      "Purchase of Project Materials",
    ],
    dividendPaid: ["Dividend Paid"],
    equityIssued: ["Proceeds from Issue of shares (incl share premium)"],
    shareBuybacks: [
      "Buyback of Shares",
      "Share Buyback",
      "Repurchase of Shares",
      "Purchase of treasury shares",
    ],
    interestReceived: ["Interest Received"],
    dividendReceived: ["Dividend Received"],
    interestNet: ["Interest (Net)"],
    depreciation: ["Depreciation"],
    plSaleInvest: ["P/L on Sales of Invest"],
    saleFixedAssets: ["Sale of Fixed Assets"],
    purchaseInvestments: ["Purchase of Investments"],
    saleInvestments: ["Sale of Investments"],
    debtProceeds: [
      "Proceed from 0ther Long Term Borrowings",
      "Proceed from Other Long Term Borrowings",
      "Proceed from Bank Borrowings",
      "Proceed from Short Tem Borrowings",
      "Proceed from Short Term Borrowings",
      "Proceed from Issue of Debentures",
    ],
    debtRepayments: [
      "Of the Long Tem Borrowings",
      "Of the Long Term Borrowings",
      "Of the short term Borrowings",
      "Of the Short Term Borrowings",
      "Of financial Liabilities",
      "On Redemption of Debenture",
    ],
  },
} as const;
