export const CapitalineMappingSpec = {
  balanceSheet: {
    totalAssets: ["Total Assets", "Total Equity and Liabilities"],
    totalStockholdersEquity: ["Total Stockholders' Equity", "Total Reported Stockholders' Equity"],
    totalEquity: ["Total Equity", "Total Shareholders Funds", "Shareholders Funds"],
    minorityInterest: ["Minority Interest"],
    financialAssets: {
      cashAndBank: [
        "Cash and Cash Equivalents",
        "Bank Balances Other Than Cash and Cash Equivalents",
        "Earmarked Balances with Bank",
        "Margin Money Balances",
        "Balances with Bank / Margin Money Balances",
        "Total Other Bank Balances",
      ],
      currentInvestments: [
        "Current Investments",
        "Investments Carried at Fair Value Through Profit Or Loss (FVTPL)",
        "Investments Carried at Fair Value Through Other Comprehensive Income(FVTOCI)",
        "Investments Carried at Amortized Cost",
        "Investments in Mutual Funds",
      ],
      longTermInvestments: [
        "Investments - Long-term",
        "Non-current Investments",
        "Total Investments",
      ],
      depositsAndRestricted: [
        "Investment in Fixed Deposits",
        "Investment in Certificate of Deposits",
        "Investment in Certificate of Deposits with Scheduled Banks",
        "Restricted Cash",
        "Restricted Deposits",
      ],
      otherFinancialAssets: [
        "Others Financial Assets - Long-term",
        "Others Financial Assets - Short-term",
        "Total Interest Receivable",
        "Interest Receivable",
        "Dividend Receivable",
        "Derivative Receivables / Forward Contract Receivable",
        "Total Short-term Other Financial Assets",
        "Total Long-term Other Financial Assets",
      ],
    },
    dtl: ["Deferred Tax Liabilities (Net)", "Deferred Tax Liability", "Net Deferred Tax Liability"],
    goodwill: ["Goodwill", "Goodwill - Net"],
    intangibleAssets: [
      "Intangible Assets",
      "Net Intangible Assets",
      "Gross Intangible Assets",
      "Brands / Trademark",
    ],
    currentAssets: ["Total Current Assets"],
    currentLiabilities: ["Total Current Liabilities"],
    nonCurrentAssets: ["Total Non-Current and Other Assets", "Total Reported Non-current Assets"],
    nonCurrentLiabilities: ["Total Reported Non-current Liabilities"],
    inventoryTop: ["Total Inventory", "Inventories"],
    inventoryComponents: [
      "Raw Materials and Components",
      "Work-in-Progress",
      "Work-in-progress",
      "Finished Goods",
      "Finished Goods / Traded Goods",
      "Stock-in-trade",
      "Stores and Spares",
      "Packing Materials",
      "Goods in Transit",
      "Opening Stock of Raw Materials",
      "Closing Stock of Raw Materials",
    ],
    tradeReceivables: ["Trade Receivables", "Total Trade Receivables", "Total Trade Debtors", "Debtor Less than 6 Month - Gross"],
    tradePayables: ["Trade Payables", "Sundry Creditors", "Sundry Creditors due to Others"],
    ppe: [
      "Net Property, plant and equipment",
      "Total Net Property, plant and equipment (not under Lease)",
      "Total PPE (not under Lease)",
      "Property, Plant and Equipment",
      "Fixed Assets",
    ],
    investmentsInSubsidiaries: [
      "Total Investment in Subsidiaries Associates and Joint Venture",
      "Investments in Subsidiaries, Associates and Joint venture",
      "Associate Companies :",
      "Equity Shares - Quoted",
      "Equity Shares Quoted",
    ],
    financialObligations: [
      "Long Term Borrowings",
      "Short Term Borrowings",
      "Lease Liabilities",
      "Others Financial Liabilities - Long-term",
      "Others Financial Liabilities - Short-term",
      "Hybrid Perpetual Securities",
      "Total Other Current Financial Liabilities",
    ],
    bridgeDebt: {
      longTermBorrowings: [
        "Long Term Borrowings",
        "Term Loans / Borrowings from Government of India",
      ],
      shortTermBorrowings: [
        "Short Term Borrowings",
      ],
      debentures: [
        "Debentures / Bonds Quoted",
        "Debentures / Bonds - Quoted",
        "Debentures / Bonds Unquoted",
        "Debentures / Bonds - Unquoted",
        "Non Convertible Debentures",
        "Convertible Debentures",
        "Total Debentures",
        "Total Bonds",
      ],
      currentMaturities: [
        "Total Current Maturities of Long-term Borrowings",
        "Total Current Maturities of Secured Long-term Debt",
        "Total Current Maturities of Unsecured Long-term Debt",
        "Unspecified Current Maturities of Long-term Debt",
        "Share of Joint Venture under Current Maturities of Long-term Borrowings",
      ],
    },
    olComponents: {
      tradePayables: ["Trade Payables", "Sundry Creditors"],
      otherCurrentLiabilities: ["Other Current Liabilities"],
      provisionsCurrent: ["Provisions"],
      provisionsLongTerm: ["Long-term Provisions"],
      currentTaxLiabilities: ["Current Tax Liabilities - Short-term"],
      nonCurrentTaxLiabilities: ["Non Current Tax Liabilities - Long-term"],
      deferredTaxLiabilitiesNet: ["Deferred Tax Liabilities (Net)"],
      otherNonCurrentLiabilities: ["Other Non-Current Liabilities"],
    },
    shareCapital: {
      authorisedShares: ["Number of Equity Shares - Authorised", "Amount of Equity Shares - Authorised"],
      issuedShares: ["Number of Equity Shares - Issued"],
      subscribedShares: ["Number of Equity Shares - Subscribed Fully Paid up", "Amount of Equity Subscribed Fully Paid up"],
      sharePremium: ["Share Premium"],
      otherEquity: ["Other Equity", "Other Comprehensive Income Reserves(Other than Retained Profits)"],
    },
    contingentLiabilities: ["Contingent Liabilities and Commitments (to the Extent Not Provided for)"],
  },
  profitLoss: {
    sales: [
      "Revenue From Operations(Net)",
      "Revenue From Operations",
      "Total Revenue from Operations",
      "Total Revenue",
      "Net Sale of Products",
      "Net Sales",
      "Net Revenue from Operations",
      "Income from Operations",
      "Revenue from Sale of Products",
    ],
    salesManufactured: ["Sales - Manufactured / Finished Goods"],
    saleOfServices: ["Sale of Services"],
    exciseDuty: ["Less: Excise Duty"],
    taxExpense: ["Tax Expenses"],
    currentTax: ["Current Tax"],
    deferredTax: ["Deferred Tax"],
    pbt: ["Profit Before Tax", "Profit Before Extraordinary", "Profit Before Exceptional Items and Tax", "Profit Before Extraordinary Items and Tax"],
    pbtBeforeExceptional: ["Profit Before Exceptional Items and Tax", "Net Profit before Tax & Extraordinary Items"],
    pat: [
      "Profit After Tax",
      "Profit/(Loss) for the period from Continuing Operations",
      "Profit Attributable to Shareholders",
      "Net Profit / Loss For The Year",
      "Profit Attributable to Ordinary Shareholders",
      "Profit After Pre-acquisition Profit",
    ],
    patOwners: ["a) Owners of the Company"],
    ociNotReclass: ["Other Comprehensive Income That Will Not Be Reclassified to Profit Or Loss"],
    ociReclass: ["Other Comprehensive Income That Will Be Reclassified to Profit Or Loss", "Other Comprehensive Income That Will Be Reclassified to Profit Or Loss :"],
    ociUnspecified: ["Other Comprehensive Income no Specification", "Other Comprehensive Income no Specification :"],
    ociEquityInstruments: ["Change in Equity Instruments"],
    tciGroup: ["Total Comprehensive Income for the Year"],
    tciNci: ["Non-Controlling Interests"],
    preferredDividend: ["Preference Dividend"],
    financeCostTop: ["Finance Cost", "Total Interest Expenses", "Finance Costs", "Interest and Finance Charges"],
    financeIncomeDirect: [
      "Interest Income",
      "Finance Income",
      "Investment Income",
    ],
    otherIncome: ["Other Income"],
    financeCostGranular: [
      "Interest",
      "Interest on Bank Borrowings",
      "Interest on Bonds and Debentures",
      "Interest on Commercial Paper",
      "Interest on Deposits",
      "Interest on External Commercial Borrowings",
      "Interest on Finance Lease",
      "Interest on Foreign Currency Loans",
      "Interest on Other Borrowings",
      "Interest on Other Loans",
      "Interest on Term / Fixed Loans",
      "Interest on Working Capital Loans",
      "Interest - Related Parties",
      "Interest and Finance Charges on Financial Liabilities",
      "Financial Charges on Financial Liabilities at Amortised Cost",
      "Bill Discounting Charges",
      "Amotisation of Borrowing Costs",
      "Other Borrowing Costs",
      "Redemption Premium",
      "Other Interest Expenses",
    ],
    exceptionalItems: ["Exceptional Items Before Tax"],
    extraordinaryItems: ["Extraordinary Items Before Tax"],
    discontinuedItems: [
      "Profit / (Loss) from Discontinuing Operations",
      "Discontinued Operations",
    ],
    cogsMaterial: ["Cost of Material Consumed", "Cost of Materials Consumed", "Consumption of Raw Materials", "Purchases of Raw Material"],
    cogsPurchases: ["Purchases of Stock-in-Trade", "Purchase of Stock-in-Trade", "Purchase of Traded Goods", "Purchase of Finished Goods", "Other Purchase"],
    cogsInventoryChange: [
      "Changes in Inventories of Finished Goods, Work-in-Progress and Stock-in-Trade",
      "Changes in Inventories",
      "Change in Inventory of Finished Goods, Work-in-Progress and Stock-in-Trade",
    ],
    totalExpenses: ["Total Expenses"],
    employeeExpense: ["Employee Benefits / Salaries & other Staff Cost", "Employee Benefit Expenses", "Employee Benefits Expense", "Employee Cost", "Salaries and Incentives"],
    otherExpenses: ["Other Expenses", "Other Operating Expenses", "Operating and Other Expenses"],
    depreciationAmortization: [
      "Depreciation and Amortization",
      "Depreciation on Tangible Assets",
      "Depreciation for the current year",
      "Depreciation and Amortisation Expense",
      "Depreciation / Amortisation",
    ],
    sgaAds: [
      "Advertisement, Marketing and Business Development",
      "Advertisements",
      "Advertisement and Sales Promotion",
      "Sales Promotion Expenses",
      "Business Promotion Expenses",
      "Selling and Distribution Expenses",
      "Sales and Distribution Expenses",
      "Total Selling and Distribution Expenses",
    ],
    sgaSellingAdmin: [
      "Selling and Administration Expenses",
      "Total Selling & Administrative Expenses",
    ],
    sgaManufacturing: [
      "Total Manufacturing / Direct Expenses",
      "Manufacturing / Direct Expenses :",
      "Job Work / Processing Charges",
      "Processing Charges",
    ],
    sgaLegal: [
      "Legal and Professional Fees",
      "Professional Fees",
      "Legal Expenses",
      "Consultancy Charges",
      "Auditors Remuneration",
    ],
    sgaRent: ["Rent", "Rent, rates & Taxes", "Lease Rent / Hire Charges Paid", "Rates and Taxes", "Lease Rentals"],
    sgaFreight: [
      "Freight Outwards and Forwarding Expenses",
      "Transportation",
      "Freight and Forwarding",
      "Packing and Forwarding",
      "Clearing and Forwarding",
      "Commission on Sales",
    ],
    sgaRepairs: [
      "Repairs and Maintenance",
      "Repairs to Building",
      "Repairs to Machinery",
      "Repairs to Other Assets",
      "Maintenance Expenses",
      "Travelling and Conveyance",
      "CSR Expenditure",
      "Royalty",
    ],
    sgaMiscellaneous: ["Total Miscellaneous Expenses"],
    sgaPower: ["Power, Fuel and Water", "Power, Oil & Fuel", "Fuel and Power", "Power and Fuel"],
    retainedEarningsProxy: [
      "Unappropriated Profits Carried Forward",
      "Unappropriated Profits Brought Forward",
      "Other Equity",
      "Profit and Loss Account Closing Balance",
      "Total Reserve & Surplus",
      "Total Reserves Excluding Revaluation Reserve",
      "Amount Available for Appropriations",
      "Opening Balance of Profit and Loss Account",
      "Profits Available for Appropriation",
    ],
    dividendDetail: [
      "Total Dividend",
      "Final Dividend Amount",
      "Interim Dividend",
      "Interim Dividend Amount",
      "Total Dividend Percentage",
      "Total Transfer to Reserves",
    ],
    epsDetail: [
      "Weighted Average Number of Shares in Issue - Diluted",
    ],
    otherItemsAliases: [
      "Share of profit/loss of associates",
      "Share of profit / (loss) of associates",
      "Share of Loss in Partnership Firm",
      "Equity accounted income",
      "Share of profit/(loss) in associate companies / joint ventures",
    ],
  },
  cashFlow: {
    cfo: ["Net Cash from Operating Activities"],
    cfi: ["Net Cash Used in Investing Activities"],
    cff: ["Net Cash Used in Financing Activities"],
    capex: [
      "Purchased of Fixed Assets",
      "Purchase of Fixed Assets",
      "Capital Expenditure",
      "Purchase of Project Materials",
    ],
    dividendPaid: ["Dividend Paid", "Payment of Final Dividend", "Prior Year Equity Dividend Paid"],
    equityIssued: ["Proceeds from Issue of shares (incl share premium)"],
    shareBuybacks: [
      "Buyback of Shares",
      "Share Buyback",
      "Repurchase of Shares",
      "Purchase of treasury shares",
    ],
    interestReceived: ["Interest Received"],
    dividendReceived: ["Dividend Received"],
    interestNet: ["Interest (Net)"],
    interestPaid: ["Interest Paid"],
    depreciation: ["Depreciation"],
    plSaleInvest: ["P/L on Sales of Invest"],
    saleFixedAssets: ["Sale of Fixed Assets"],
    purchaseInvestments: ["Purchase of Investments"],
    saleInvestments: ["Sale of Investments"],
    directTaxesPaid: ["Direct Taxes Paid"],
    opProfitBeforeWC: ["Op. Profit before Working Capital Changes"],
    cashFromOperations: ["Cash Generated from/(used in) Operations"],
    cashFlowBeforeExtraordinary: ["Cash Flow before Extraordinary Items"],
    workingCapitalChanges: ["Total Working Capital Changes", "Total (OP before Working Capital Changes)"],
    tradeReceivablesChange: ["Trade & 0th receivables"],
    inventoriesChange: ["Inventories"],
    tradePayablesChange: ["Trade Payables"],
    investInSubsidiaries: ["Invest.In Subsidiaires", "Investment in Group Cos"],
    netCashChange: ["Net Inc/(Dec) in Cash and Cash Equivalent"],
    openingCash: ["Cash and Cash Equivalents at Beginning of the year"],
    closingCash: ["Cash and Cash Equivalents at End of the year"],
    debtProceeds: [
      "Proceed from 0ther Long Term Borrowings",
      "Proceed from Other Long Term Borrowings",
      "Proceed from Bank Borrowings",
      "Proceed from Short Tem Borrowings",
      "Proceed from Short Term Borrowings",
      "Proceed from Issue of Debentures",
      "Proceed from Deposits",
    ],
    debtRepayments: [
      "Of the Long Tem Borrowings",
      "Of the Long Term Borrowings",
      "Of the short term Borrowings",
      "Of the Short Term Borrowings",
      "Of financial Liabilities",
      "On Redemption of Debenture",
    ],
    bridgeDebtProceeds: [
      "Proceed from 0ther Long Term Borrowings",
      "Proceed from Other Long Term Borrowings",
      "Proceed from Bank Borrowings",
      "Proceed from Short Tem Borrowings",
      "Proceed from Short Term Borrowings",
      "Proceed from Issue of Debentures",
    ],
    bridgeDebtRepayments: [
      "Of the Long Tem Borrowings",
      "Of the Long Term Borrowings",
      "Of the short term Borrowings",
      "Of the Short Term Borrowings",
      "On Redemption of Debenture",
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BANK / FINANCIAL INSTITUTION SPECIFIC MAPPINGS
  // These labels are populated for banks/NBFCs but null for industrials.
  // bankPipeline.ts uses these arrays directly — keep in sync.
  // ═══════════════════════════════════════════════════════════════
  bankBalanceSheet: {
    // ── Balance sheet totals ──────────────────────────────────────
    totalAssets: ["Total Assets", "Total Assets/Liabilities"],
    totalEquity: [
      "Total Equity",
      "Total Shareholders Funds",
      "Total Shareholders' Funds",
      "Total Stockholders' Equity",
      "Total Reported Stockholders' Equity",
    ],

    // ── Core earning assets ───────────────────────────────────────
    advances: [
      "Advances",
      "Total Advances",
      "Loans and Advances to Customers",
      "Total Loans Given",
      "Advances :",
      // NBFCs report loan books under different labels; aliasing them
      // here means the bank pipeline picks them up regardless of subtype.
      "Loan Assets",
      "Finance Receivables",
      "Hire Purchase Assets",
      "Lease Assets",
    ],
    investments: [
      "Investments",
      "Total Investments",
      "Investments of Banking Business",
    ],
    investmentsGovernment: ["Investments in Government or Trust securities"],
    investmentsBonds: ["Investments in Debentures or Bonds"],
    investmentsOther: ["Other Current Investments"],

    // ── Funding sources ───────────────────────────────────────────
    deposits: ["Deposits", "Total Deposits", "Total Long-term Secured Deposits"],
    // CASA sub-components — Capitaline breaks deposits into demand/savings/term.
    // demandDeposits = current accounts (zero-cost), savingsDeposits = savings accounts.
    // CASA ratio = (demand + savings) / total deposits.
    demandDeposits: [
      "Demand Deposits",
      "Current Deposits",
      "Deposits - Demand",
      "Current Account Deposits",
      // Capitaline bank BS format (HDFC, ICICI): current accounts sub-line
      "in Current Accounts",
    ],
    savingsDeposits: [
      "Savings Deposits",
      "Savings Bank Deposits",
      "Deposits - Savings",
      "Savings Account Deposits",
    ],
    borrowings: ["Borrowings", "Total Borrowings"],
    nonConvertibleDebentures: ["Non Convertible Debentures"],
    termLoansFromBanks: ["Term Loans - Banks"],
    termLoansFromInstitutions: ["Term Loans - Institutions"],
    termLoansFromOthers: ["Term Loans - Others Parties"],

    // ── Cash & liquidity ──────────────────────────────────────────
    cashAndBalanceWithRBI: [
      "Cash and Balance with RBI",
      "Cash and Balances with Reserve Bank of India",
    ],
    cashOnHand: ["Cash on Hand"],
    balancesWithBanks: ["Balances with Banks"],
    balancesInCurrentAccounts: ["in Current Accounts"],

    // ── Insurance (HDFC group) ────────────────────────────────────
    policyHoldersLiabilities: ["Policy Holders Accounts - Liabilities"],
    policyholderFunds: ["Policyholders Funds", "Life Assurance Fund", "Investments of Life Insurance Business", "Policy Holder's Investments (Insurance Business)", "Policy Holders Accounts - Liabilities"],

    // ── Contingent liabilities (off-balance sheet) ────────────────
    guaranteesGiven: ["Guarantees given on behalf of constituents - in India"],
    forwardExchangeContracts: ["Liability on Account of Outstanding Forward Exchange Contracts"],
    acceptancesEndorsements: ["Acceptances, Endorsements and Other obligations"],
    totalContingentLiabilities: ["Total Contingent Liabilities"],

    // ── Provisions ────────────────────────────────────────────────
    provisionForStandardAssets: ["Provision for Standard Assets as per NHB Norms"],
  },

  bankProfitLoss: {
    // ── Interest income (NII components) ─────────────────────────
    interestIncome: [
      "Interest Earned",
      "Interests Income (Operating)",
      "Interest Income",
      "Total Revenue from Operations",
      "Interest / Discount on Advances / Bills",
    ],
    otherInterestIncome: ["Other Interest Income"],
    feeAndCommissionIncome: ["Fee and Commission Income"],

    // ── Interest expense ──────────────────────────────────────────
    interestExpended: ["Interest Expended", "Interest Expense", "Total Interest Expenses"],
    interestOnDeposits: ["Interest on Deposits"],

    // ── Non-interest income ───────────────────────────────────────
    otherIncome: ["Other Income", "Non-Interest Income", "Other Non Operating Income", "Total Other Operating Revenue"],
    profitOnSaleOfInvestments: ["Profit on Sale of Investments"],
    forexGainLoss: ["Net Gain / Loss on Foreign Currency Transaction"],
    otherNonOperatingIncome: ["Other Non Operating Income"],

    // ── Operating expenses ────────────────────────────────────────
    operatingExpenses: [
      "Operating Expenses",
      "Payments to and Provisions for Employees",
      "Total Operating Expenses",
      "Cost of Insurance Operation (Insurance Business)",
      "Operating Expenses Related to Insurance Business",
      "Net Commission",
      "Commission",
    ],
    salariesAndIncentives: ["Salaries and Incentives"],
    totalSellingAdminExpenses: ["Total Selling & Administrative Expenses"],
    totalMiscExpenses: ["Total Miscellaneous Expenses"],

    // ── Provisions & credit cost ──────────────────────────────────
    provisions: [
      "Provisions and Contingencies",
      "Provision for NPA",
      "Prov. & W/O (Net)",
      "Other Provisions and Write-offs",
      "Provision for Doubtful Loan / Deposit / Advances",
      "Impairment on Financial Instruments",
      "Loss Allowance on Loans",
    ],
    otherProvisionsWriteoffs: ["Other Provisions and Write-offs"],

    // ── Profitability ─────────────────────────────────────────────
    profitBeforeTax: [
      "Profit Before Tax",
      "Net Profit before Tax & Extraordinary Items",
      "Profit Before Exceptional Items and Tax",
    ],
    profitAfterTax: ["Profit After Tax", "Net Profit"],
    profitAttributableToShareholders: [
      "Profit Attributable to Shareholders",
      "Profit Attributable to Ordinary Shareholders",
    ],
    minorityInterest: ["Minority Interest After Net Profit"],

    // ── Per share ─────────────────────────────────────────────────
    weightedAvgSharesBasic: ["Weighted Average Number of Shares in Issue - Basic"],
    weightedAvgSharesDiluted: ["Weighted Average Number of Shares in Issue - Diluted"],

    // ── Dividends ─────────────────────────────────────────────────
    totalDividend: ["Total Dividend"],

    // ── Insurance Specific ────────────────────────────────────────
    premiumEarned: ["Premium Earned (Net)", "Premium Earned", "Gross Written Premium", "Net Earned Premium", "Premium Earned Net"],
    claimsExpense: ["Claims Expenses", "Claims Incurred", "Net Claims Incurred", "Claims Incurred (Net)", "Net Claims/Benefits Paid", "Total Claims Paid"],
    investmentIncome: ["Investment Income", "Income from Investments", "Interest & Dividend Income", "Investment Income (Insurance Business)"],
  },
} as const;
