// GENERATED FROM registry.json by scripts/sync-tickers.cjs
// DO NOT EDIT BY HAND.
export const NSE_SYMBOL_REGISTRY = {
  "Asian Paints": "ASIANPAINT",
  "Avenue Supermarts": "DMART",
  "Bajaj Finance": "BAJFINANCE",
  "Bharti Airtel": "BHARTIARTL",
  "Britannia Industries": "BRITANNIA",
  "Cholamandalam Investment": "CHOLAFIN",
  "Dabur India": "DABUR",
  "Grasim Industries": "GRASIM",
  "HDFC Bank": "HDFCBANK",
  "HDFC Life Insurance Company Ltd": "HDFCLIFE",
  "Hindustan Unilever": "HINDUNILVR",
  "ICICI Bank": "ICICIBANK",
  "Infosys": "INFY",
  "ITC": "ITC",
  "KOTAKBANK": "KOTAKBANK",
  "Larsen & Toubro Ltd": "LT",
  "Life Insurance Corporation of India": "LICI",
  "Mahindra & Mahindra": "M&M",
  "Maruti Suzuki India Ltd": "MARUTI",
  "Muthoot Finance": "MUTHOOTFIN",
  "Nestlé India": "NESTLEIND",
  "NTPC": "NTPC",
  "Paytm": "PAYTM",
  "Power Grid Corporation of India Ltd": "POWERGRID",
  "Reliance Industries": "RELIANCE",
  "SBIN": "SBIN",
  "Shriram Finance": "SHRIRAMFIN",
  "Sun Pharmaceutical Industries Ltd": "SUNPHARMA",
  "Tata Consultancy Services Ltd": "TCS",
  "Tata Steel": "TATASTEEL",
  "Titan Company": "TITAN",
  "UltraTech Cement Ltd": "ULTRACEMCO",
  "Vodafone Idea Ltd": "IDEA",
};
