import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import QualityReport from "../QualityReport";
import { buildAnalysisTraceability } from "../../engine/analysisTraceability";
import { getAnalysisPolicyVersions } from "../../engine/policyVersions";
import { DEFAULT_CONFIG, RecastPeriod } from "../../engine/types";

function mkQualityPeriod(period_end: string, overrides: Partial<RecastPeriod> = {}): RecastPeriod {
  return {
    period_end,
    bs: {
      TA: 1000,
      CSE: 600,
      MI: 0,
      FA: 150,
      FO: 150,
      OA: 850,
      OL: 250,
      OL_TradePayables: 80,
      OL_OtherCurrentLiabilities: 50,
      OL_ProvisionsCurrent: 10,
      OL_ProvisionsLongTerm: 10,
      OL_CurrentTaxLiabilities: 10,
      OL_NonCurrentTaxLiabilities: 10,
      OL_DeferredTaxLiabilitiesNet: 5,
      OL_OtherNonCurrentLiabilities: 75,
      NOA: 600,
      NFO: 0,
      DTL: 5,
      PensionObl: 0,
      OL_ex_DTL: 245,
      Goodwill: 0,
      CurrentAssets: 400,
      CurrentLiabilities: 220,
      Inventory: 90,
      TradeReceivables: 110,
      TradePayables: 80,
      PPE: 320,
      LIFO_reserve: 0,
      separationScore: 90,
      OA_PPE: 320,
      OA_ROU: 0,
      OA_Goodwill: 0,
      OA_OtherIntangibles: 0,
      OA_Inventory: 90,
      OA_TradeReceivables: 110,
      OA_DTA: 0,
      OA_CWIP: 0,
      OA_Other: 330,
    },
    is: {
      Sales: 900,
      TaxExpense: 30,
      taxRate: 0.25,
      PAT: 90,
      OCI: 0,
      TCI: 90,
      TCI_NCI: 0,
      CNI: 90,
      FinanceCost: 12,
      FinanceIncome: 2,
      FinanceIncomeRung: 1,
      PreferredDividend: 0,
      NFE: 10,
      OI: 100,
      OtherItems: 0,
      OI_from_sales: 100,
      MII: 0,
      COGS: 600,
    },
    cu: {
      UOI: 0,
      CoreOI: 100,
      UFE: 0,
      CoreNFE: 10,
      ExceptionalItemsAfterTax: 0,
      OCITotal: 0,
    },
    cf: {
      CFO: 120,
      Capex: 40,
      DividendPaid: 20,
      EquityIssued: 0,
      ShareBuybacks: 0,
      InterestReceived: 0,
      DividendReceived: 0,
      FCF_accounting: 60,
      FCF_cash: 80,
      d_t: 20,
      d_t_formula: 20,
      d_t_discrepancy: 0,
      EBITDA: 140,
    },
    quality: {
      piotroski_total: 7,
      beneish_dsri: 1,
      beneish_gmi: 1,
      beneish_aqi: 1,
      beneish_sgi: 1,
      beneish_depi: 1,
      beneish_sgai: 1,
      beneish_lvgi: 1,
      beneish_tata: 0.02,
      altman_zprime: 3.1,
      altman_wc_ta: 0.18,
      altman_re_ta: 0.22,
      altman_ebit_ta: 0.12,
      altman_bve_tl: 1.5,
      altman_s_ta: 0.9,
      beneish_mscore: -2.0,
      zmijewski_roa: 0.09,
      zmijewski_leverage: 0.4,
      zmijewski_liquidity: 1.5,
      zmijewski_xscore: -2.2,
      zmijewski_prob_distress: 0.08,
      ohlson_size: 6,
      ohlson_leverage: 0.4,
      ohlson_liquidity: 1.5,
      ohlson_roe_neg: false,
      ohlson_chin: 0,
      ohlson_oscore: -1.9,
      ohlson_prob_distress: 0.07,
      sloan_wc_accruals: 0.03,
      sloan_lt_accruals: 0.01,
      sloan_total_accruals: 0.04,
      accrual_reliability_score: 0.86,
      cash_earnings_quality_index: 1.1,
      operating_leverage: 1.2,
      conservative_accounting_score: 72,
      revenue_quality_flags: [],
      piotroski_roa: 1,
      piotroski_delta_roa: 1,
      piotroski_cfo: 1,
      piotroski_accrual: 1,
      piotroski_leverage: 1,
      piotroski_liquidity: 1,
      piotroski_dilution: 1,
      piotroski_margin: 0,
      piotroski_turnover: 0,
    },
    ...overrides,
  };
}

describe("QualityReport", () => {
  it("renders the shared traceability trust gate ahead of quality metrics", () => {
    const data = [
      mkQualityPeriod("2024-03-31"),
      mkQualityPeriod("2025-03-31"),
    ];
    const traceability = buildAnalysisTraceability({
      generatedAt: "2026-04-03T11:00:00.000Z",
      runId: "run-quality",
      companyId: "ITC",
      sourceMode: "json",
      recastData: data,
      config: DEFAULT_CONFIG,
      rawData: [
        {
          company_id: "ITC",
          period_end: "2024-03-31",
          raw_metric_values: {
            "Total Assets__BalanceSheet": 1000,
            "Total Equity__BalanceSheet": 600,
            "Revenue From Operations(Net)__ProfitLoss": 900,
            "Profit After Tax__ProfitLoss": 90,
          },
        },
        {
          company_id: "ITC",
          period_end: "2025-03-31",
          raw_metric_values: {
            "Total Assets__BalanceSheet": 1000,
            "Total Equity__BalanceSheet": 600,
            "Revenue From Operations(Net)__ProfitLoss": 900,
            "Profit After Tax__ProfitLoss": 90,
          },
        },
      ],
      periodCount: 2,
      latestPeriod: "2025-03-31",
      policyVersions: getAnalysisPolicyVersions(),
    });

    const html = renderToStaticMarkup(<QualityReport data={data} traceability={traceability} />);

    expect(html).toContain("Quality Trust Gate");
    expect(html).toContain("Economically plausible");
    expect(html).toContain("Quality Score Trends");
  });
});
