import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import RecastStatements from "../RecastStatements";
import { buildAnalysisTraceability } from "../../engine/analysisTraceability";
import { getAnalysisPolicyVersions } from "../../engine/policyVersions";
import { DEFAULT_CONFIG, RecastPeriod } from "../../engine/types";

function mkStatementsPeriod(period_end: string): RecastPeriod {
  return {
    period_end,
    bs: {
      TA: 1000,
      CSE: 600,
      MI: 0,
      FA: 150,
      FO: 150,
      OA: 850,
      OL: 250,
      OL_TradePayables: 80,
      OL_OtherCurrentLiabilities: 50,
      OL_ProvisionsCurrent: 10,
      OL_ProvisionsLongTerm: 10,
      OL_CurrentTaxLiabilities: 10,
      OL_NonCurrentTaxLiabilities: 10,
      OL_DeferredTaxLiabilitiesNet: 5,
      OL_OtherNonCurrentLiabilities: 75,
      NOA: 600,
      NFO: 0,
      DTL: 5,
      PensionObl: 0,
      OL_ex_DTL: 245,
      Goodwill: 0,
      CurrentAssets: 400,
      CurrentLiabilities: 220,
      Inventory: 90,
      TradeReceivables: 110,
      TradePayables: 80,
      PPE: 320,
      LIFO_reserve: 0,
      separationScore: 90,
      OA_PPE: 320,
      OA_ROU: 0,
      OA_Goodwill: 0,
      OA_OtherIntangibles: 0,
      OA_Inventory: 90,
      OA_TradeReceivables: 110,
      OA_DTA: 0,
      OA_CWIP: 0,
      OA_Other: 330,
    },
    is: {
      Sales: 900,
      TaxExpense: 30,
      taxRate: 0.25,
      PAT: 90,
      OCI: 0,
      TCI: 90,
      TCI_NCI: 0,
      CNI: 90,
      FinanceCost: 12,
      FinanceIncome: 2,
      FinanceIncomeRung: 1,
      PreferredDividend: 0,
      NFE: 10,
      OI: 100,
      OtherItems: 0,
      OI_from_sales: 100,
      MII: 0,
      COGS: 600,
    },
    cu: {
      UOI: 0,
      CoreOI: 100,
      UFE: 0,
      CoreNFE: 10,
      ExceptionalItemsAfterTax: 0,
      OCITotal: 0,
    },
    cf: {
      CFO: 120,
      Capex: 40,
      DividendPaid: 20,
      EquityIssued: 0,
      ShareBuybacks: 0,
      InterestReceived: 0,
      DividendReceived: 0,
      DebtProceeds: 0,
      DebtRepayment: 0,
      SaleFixedAssets: 0,
      PurchaseInvestments: 0,
      SaleInvestments: 0,
      FCF_accounting: 60,
      FCF_cash: 80,
      d_t: 20,
      d_t_formula: 20,
      d_t_discrepancy: 0,
      EBITDA: 140,
    },
    ratios: {
      ROCE: 0.15,
      RNOA: 0.14,
      NBC: 0.04,
      SPREAD: 0.10,
      FLEV: 0,
      PM: 0.11,
      ATO: 1.4,
      SalesPM: 0.11,
      ATO_star: 1.2,
      OtherItemsRatio: 0,
      ROCE_bridge_residual: 0.0,
      io: 0,
      ROOA: 0.12,
      OLLEV: 0.25,
      OLSPREAD: 0.02,
      RNOA_check: 0.14,
      ROTCE: 0.16,
      MSR: 1.0,
      CoreSalesPM: 0.10,
      CoreOtherItems_OA: 0,
      UOI_OA: 0,
      CoreNBC: 0.04,
      UFE_NFO: 0,
      CoreSPREAD: 0.08,
      ROCE_eq16_reconstructed: 0.15,
      ROCE_eq16_error: 0.0,
      eq16_step1_residual: 0,
      eq16_step2_residual: 0,
      eq16_step3_residual: 0,
      eq16_flag: "OK",
      eq16_diagnosis: null,
      ROOA_spec: 0.12,
      imputed_io_spec: 0,
      required_return_per_sales: 0.03,
      value_creating_margin: 0.08,
      CSE_eq8_check: 600,
      CSE_eq8_error_pct: 0,
      current_ratio: 1.8,
      quick_ratio: 1.4,
      days_receivable: 45,
      days_payable: 35,
      days_inventory: 55,
      cash_conversion_cycle: 65,
      accrual_ratio_bs: 0.03,
      accrual_ratio_cf: 0.02,
      cash_conversion_ratio: 1.15,
      interest_coverage: 8.3,
      NOA_growth: 0.04,
      CNI_growth: 0.05,
      OI_growth: 0.06,
      Sales_growth: 0.06,
      noaSmall: false,
      separationScore: 90,
      accrual_regime: "NORMAL",
      dirty_surplus: 0,
      dirty_surplus_pct_cse: 0,
    },
  };
}

describe("RecastStatements", () => {
  it("renders the shared traceability trust gate ahead of the recast statements", () => {
    const data = [
      mkStatementsPeriod("2024-03-31"),
      mkStatementsPeriod("2025-03-31"),
    ];
    const traceability = buildAnalysisTraceability({
      generatedAt: "2026-04-03T14:00:00.000Z",
      runId: "run-statements",
      companyId: "ITC",
      sourceMode: "json",
      recastData: data,
      config: DEFAULT_CONFIG,
      rawData: [
        {
          company_id: "ITC",
          period_end: "2024-03-31",
          raw_metric_values: {
            "Total Assets__BalanceSheet": 1000,
            "Total Equity__BalanceSheet": 600,
            "Revenue From Operations(Net)__ProfitLoss": 900,
            "Profit After Tax__ProfitLoss": 90,
          },
        },
        {
          company_id: "ITC",
          period_end: "2025-03-31",
          raw_metric_values: {
            "Total Assets__BalanceSheet": 1000,
            "Total Equity__BalanceSheet": 600,
            "Revenue From Operations(Net)__ProfitLoss": 900,
            "Profit After Tax__ProfitLoss": 90,
          },
        },
      ],
      periodCount: 2,
      latestPeriod: "2025-03-31",
      policyVersions: getAnalysisPolicyVersions(),
    });

    const html = renderToStaticMarkup(<RecastStatements data={data} traceability={traceability} />);

    expect(html).toContain("Statements Trust Gate");
    expect(html).toContain("Economically plausible");
    expect(html).toContain("Recast Balance Sheet");
    expect(html).toContain("Free Cash Flow &amp; Dividends");
  });
});
