import { ValuationModelRegistry } from "./registry";
import type {
  ModelDataRequirement,
  ModelGuardDefinition,
  ModelImplementationReference,
  ModelRequirementKind,
  ModelRequirementPurpose,
  ValuationModelDefinition,
  ValuationModelFamily,
} from "./types";

export const CURRENT_MODEL_CATALOG_VERSION = "2026-07-10-current-models-v2" as const;

const INDUSTRIAL_FAMILIES = ["industrial", "telecom", "utility"] as const satisfies readonly ValuationModelFamily[];
const FI_FAMILIES = ["bank", "nbfc", "insurance"] as const satisfies readonly ValuationModelFamily[];

function requirement(
  requirementId: string,
  kind: ModelRequirementKind,
  keys: readonly string[],
  minimumObservations: number,
  description: string,
  purpose: ModelRequirementPurpose = "compute",
): ModelDataRequirement {
  return { requirementId, kind, keys, minimumObservations, purpose, description };
}

function guard(
  guardId: string,
  description: string,
  blocksResult = true,
): ModelGuardDefinition {
  return { guardId, guardVersion: "1.0.0", blocksResult, description };
}

function implementation(
  modulePath: string,
  exportName: string,
  outputPath: string | null,
  integration: ModelImplementationReference["integration"],
  note: string,
): ModelImplementationReference {
  return { modulePath, exportName, outputPath, integration, note };
}

function define(definition: ValuationModelDefinition): ValuationModelDefinition {
  return definition;
}

const TERMINAL_SPREAD_GUARD = guard(
  "terminal.discount-growth-spread",
  "The applicable discount rate must exceed terminal growth by the policy minimum.",
);
const FINITE_VALUE_GUARD = guard(
  "output.finite-valuation",
  "At least one published enterprise, equity, or per-share value must be finite.",
);
const POSITIVE_SHARE_GUARD = guard(
  "share-basis.positive",
  "Per-share publication requires a resolved, positive share basis.",
);

const PENMAN_REQUIREMENTS = [
  requirement("industrial.recast-history", "fact", ["CSE", "NOA", "NFO", "CNI", "OI"], 2, "At least two reconciled industrial periods."),
  requirement("industrial.forecast-case", "assumption", ["sales-growth", "margin", "reinvestment", "ke", "kw", "terminal-growth"], 1, "A validated forecast case and capital costs."),
  requirement("common.share-basis", "fact", ["diluted-shares"], 1, "Resolved diluted shares for per-share output.", "enrichment"),
] as const;

const CURRENT_MODEL_DEFINITIONS_MUTABLE: ValuationModelDefinition[] = [
  define({
    modelId: "industrial.penman.residual-income",
    modelVersion: "legacy-unversioned",
    label: "Penman residual income",
    description: "Equity residual-income valuation anchored on common shareholders' equity.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "V_RE_CV3", "wired", "Computed for industrial scenario cards and published as the primary equity accrual lens."),
    lifecycleNote: "Runtime-wired today; still shares forecast and recast evidence with the ReOI and Penman cross-check variants.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.penman.residual-operating-income",
    modelVersion: "legacy-unversioned",
    label: "Penman residual operating income",
    description: "Enterprise residual-operating-income valuation bridged to common equity.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "V_ReOI_CV03", "wired", "Computed alongside residual income from the same recast and forecast."),
    lifecycleNote: "Runtime-wired, but deliberately shares one evidence group with residual income because it is not independent corroboration.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.penman.fcff-cross-check",
    modelVersion: "legacy-unversioned",
    label: "Penman FCFF cross-check",
    description: "FCFF rearrangement produced by the Penman forecast/recast path.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "fcf.EV_FCFF", "wired", "Output exists in every Penman valuation result but is treated as a correlated cross-check."),
    lifecycleNote: "Categorized diagnostic, not an independent intrinsic model, because it is derived from the same clean-surplus algebra.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.penman.fcfe-cross-check",
    modelVersion: "legacy-unversioned",
    label: "Penman FCFE cross-check",
    description: "FCFE rearrangement produced by the Penman forecast/recast path.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "fcf.V_FCFE", "wired", "Output exists in the Penman valuation result as a correlated cross-check."),
    lifecycleNote: "Diagnostic-only for evidence counts; it does not create a second independent cash-flow family.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.penman.aeg-cross-check",
    modelVersion: "legacy-unversioned",
    label: "Abnormal earnings growth cross-check",
    description: "AEG valuation emitted from the common Penman valuation input.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "aeg.V_AEG", "wired", "Published in ValuationResult but not treated as independent evidence."),
    lifecycleNote: "Runtime-computed but cataloged as a correlated diagnostic to prevent six-formula model-count inflation.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.penman.ddm-cross-check",
    modelVersion: "legacy-unversioned",
    label: "Penman dividend cross-check",
    description: "Dividend-discount output derived inside the shared Penman forecast path.",
    inputContract: "penman-valuation-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "accrual-residual-income",
    requirements: PENMAN_REQUIREMENTS,
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/PenmanNissimEngine.ts", "computeValuation", "perShare.intrinsic_ddm_per_share", "wired", "A cross-check field in the shared valuation result, not a separately sourced distribution model."),
    lifecycleNote: "Diagnostic because current dividends/forecast assumptions are not independently sourced from the main accrual case.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.owner-earnings-dcf",
    modelVersion: "legacy-unversioned",
    label: "Owner-earnings DCF",
    description: "Scenario DCF based on CFO less estimated maintenance capital expenditure.",
    inputContract: "owner-earnings-scenario-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "owner-earnings-cash",
    requirements: [
      requirement("industrial.owner-earnings", "fact", ["CFO", "capex", "depreciation", "diluted-shares"], 1, "Positive owner earnings and a share basis."),
      requirement("industrial.owner-earnings-growth-path", "assumption", ["sales-growth", "ke", "terminal-growth"], 1, "A scenario growth and discount-rate path."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/valuationCommandCenter/solvers.ts", "computeOwnerEarningsDcf", null, "wired", "Executed for each industrial command-center scenario before the scenario headline is aggregated."),
    lifecycleNote: "Wired and cash-oriented, though maintenance capex remains an estimated input whose evidence must be surfaced.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.cash-statement-fcff-dcf",
    modelVersion: "legacy-unversioned",
    label: "Cash-statement FCFF DCF",
    description: "Independent DCF using directly reported CFO less capex, with an enterprise-to-equity bridge.",
    inputContract: "cash-statement-fcff-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "cash-statement",
    requirements: [
      requirement("industrial.cash-fcf-history", "fact", ["FCF-cash", "NFO", "minority-interest"], 2, "At least two finite direct cash-flow observations plus the equity bridge."),
      requirement("industrial.structural-kw", "assumption", ["kw", "terminal-growth"], 1, "Structural WACC and terminal growth."),
      requirement("common.share-basis", "fact", ["diluted-shares"], 1, "Resolved shares for per-share output.", "enrichment"),
    ],
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/cashFlowDcf.ts", "computeCashFlowDcf", null, "wired", "Called directly by the industrial command center and evidence-weighted synthesis."),
    lifecycleNote: "Wired as the current genuinely direct cash-statement evidence family and returns an honest null when guards fail.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.graham-dodd-epv",
    modelVersion: "legacy-unversioned",
    label: "Graham-Dodd earnings power value",
    description: "Normalized no-growth earnings-power floor with a net-financial-obligations bridge.",
    inputContract: "industrial-epv-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "earnings-power",
    requirements: [
      requirement("industrial.normalized-operating-history", "fact", ["core-OI", "tax-rate", "capex", "depreciation", "NFO"], 3, "Operating history for normalized earnings power."),
      requirement("industrial.epv-capital-cost", "assumption", ["ke", "kw"], 1, "Resolved capital cost."),
      requirement("common.share-basis", "fact", ["diluted-shares"], 1, "Resolved shares for per-share output.", "enrichment"),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/grahamDoddEPV.ts", "computeEPV", null, "wired", "Computed in V3 analytics and the command center as a no-growth anchor."),
    lifecycleNote: "Wired as an intrinsic floor; not assumed independent from all accrual inputs merely because its formula differs.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.segment-sotp",
    modelVersion: "legacy-unversioned",
    label: "Industrial segment SOTP",
    description: "Segment-weighted sum-of-parts using parsed segments or an explicit preset.",
    inputContract: "industrial-segment-sotp-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "segment-sotp",
    requirements: [
      requirement("industrial.segment-evidence", "segment", ["segment-name", "segment-operating-profit", "segment-assets"], 2, "At least two identified business segments."),
      requirement("industrial.segment-capital-cost", "assumption", ["segment-ke", "segment-terminal-growth"], 1, "Segment capital-cost and terminal assumptions."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sotpValuation.ts", "buildSOTPValuation", null, "wired", "The command center prefers parsed segment data and otherwise requires an explicit preset."),
    lifecycleNote: "Wired, but applicability requires actual segment inputs; a company-type or strategy label is never computation evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.ev-ebitda-peer",
    modelVersion: "legacy-unversioned",
    label: "Peer EV/EBITDA",
    description: "Peer-median EV/EBITDA cross-check bridged from enterprise to equity value.",
    inputContract: "industrial-peer-ev-ebitda-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "relative",
    lifecycle: "production",
    independenceGroup: "peer-market",
    requirements: [
      requirement("industrial.ebitda-anchor", "fact", ["EBITDA", "NFO"], 1, "Current EBITDA and net debt."),
      requirement("industrial.ev-ebitda-peers", "market", ["peer-ev-ebitda"], 1, "At least one finite positive peer multiple."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/evEbitdaCrossCheck.ts", "computeEvEbitdaCrossCheck", "equityFromMedian", "wired", "Computed by the command center when configured peer multiples are available."),
    lifecycleNote: "Wired relative context and intentionally separate from intrinsic evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.historical-relative-multiples",
    modelVersion: "legacy-unversioned",
    label: "Industrial relative multiples",
    description: "Current-price multiples against historical fundamentals and optional sector medians.",
    inputContract: "industrial-relative-multiples-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "relative",
    lifecycle: "production",
    independenceGroup: "peer-market",
    requirements: [
      requirement("industrial.relative-history", "fact", ["CNI", "CSE", "sales", "EBITDA", "NFO"], 2, "Historical positive fundamentals."),
      requirement("common.market-cap", "market", ["market-cap", "market-price"], 1, "Current market value."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/relativeValuation.ts", "computeIndustrialMultiples", "impliedFairValueComposite", "wired", "Computed in the V3 analytics bundle when market price and shares resolve."),
    lifecycleNote: "Wired market context; its historical bands use current price against historical fundamentals and are labeled accordingly.",
    replacementModelId: null,
  }),
  define({
    modelId: "cross-family.peer-relative",
    modelVersion: "legacy-unversioned",
    label: "Registry peer relative valuation",
    description: "Cross-company peer ranking and multiple-implied values from the comparison registry.",
    inputContract: "comparison-registry-relative-v1",
    families: ["cross-family"],
    category: "relative",
    lifecycle: "production",
    independenceGroup: "peer-market",
    requirements: [
      requirement("registry.comparable-peers", "market", ["peer-company-record", "peer-fundamentals"], 1, "At least one non-blocked comparable peer."),
      requirement("common.market-price", "market", ["market-price"], 1, "Target market price for margin-of-safety context.", "enrichment"),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/peerRelativeValuation.ts", "computePeerRelativeValuation", "compositeFairValue", "wired", "Invoked by the comparison report against registry peers."),
    lifecycleNote: "Wired on the comparison surface; it remains one peer-market group regardless of how many multiples are emitted.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.reverse-dcf",
    modelVersion: "legacy-unversioned",
    label: "Industrial reverse DCF",
    description: "Back-solves the growth, return, and fade assumptions embedded in current market price.",
    inputContract: "industrial-reverse-dcf-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "market-implied",
    lifecycle: "production",
    independenceGroup: "market-price",
    requirements: [
      requirement("industrial.reverse-dcf-history", "fact", ["RNOA", "NOA", "NFO", "CSE"], 4, "At least four industrial periods."),
      requirement("common.market-price-and-shares", "market", ["market-price", "diluted-shares"], 1, "Current market price and shares."),
    ],
    guards: [],
    implementation: implementation("src/engine/reverseDCF.ts", "computeReverseDCF", null, "wired", "Invoked by useAdvancedModels and displayed as implied expectations."),
    lifecycleNote: "Wired, but categorically market-implied: it cannot enter intrinsic model counts or confidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.reverse-dcf-monte-carlo",
    modelVersion: "legacy-unversioned",
    label: "Reverse DCF Monte Carlo",
    description: "Distribution of terminal growth implied by the current price under sampled margins, growth, and WACC.",
    inputContract: "reverse-dcf-monte-carlo-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "market-implied",
    lifecycle: "production",
    independenceGroup: "market-price",
    requirements: [
      requirement("industrial.revenue-margin-history", "fact", ["sales", "FCF-cash"], 2, "Revenue, cash margins, and historical growth."),
      requirement("common.market-price-and-shares", "market", ["market-price", "diluted-shares"], 1, "Current market price and shares."),
    ],
    guards: [],
    implementation: implementation("src/engine/valuation/reverseDcfMonteCarlo.ts", "runReverseDcfMonteCarlo", null, "wired", "Built in the industrial command center when market inputs resolve."),
    lifecycleNote: "Wired expectations diagnostic; stochastic sampling does not convert price-derived evidence into intrinsic evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.loss-maker-revenue-multiple",
    modelVersion: "legacy-unversioned",
    label: "Loss-maker revenue multiple",
    description: "EV/sales anchor for companies with persistently non-positive earnings.",
    inputContract: "loss-maker-valuation-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "relative",
    lifecycle: "production",
    independenceGroup: "peer-market",
    requirements: [
      requirement("industrial.loss-maker-history", "fact", ["sales", "CNI", "NFO"], 2, "Loss-making history and current revenue."),
      requirement("industrial.ev-sales-multiple", "market", ["peer-ev-sales", "sector-ev-sales"], 1, "A configured or disclosed EV/sales multiple.", "enrichment"),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/lossMakerValuation.ts", "computeLossMakerValuation", "revenueMultiple.perShareValue", "wired", "Computed by the main pipeline only after the loss-maker applicability test."),
    lifecycleNote: "Wired relative anchor, not a primary intrinsic model; sector defaults must remain visible as low-evidence assumptions.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.loss-maker-reverse-dcf",
    modelVersion: "legacy-unversioned",
    label: "Loss-maker reverse DCF",
    description: "Market-implied margin and revenue path for a loss-making issuer.",
    inputContract: "loss-maker-valuation-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "market-implied",
    lifecycle: "production",
    independenceGroup: "market-price",
    requirements: [
      requirement("industrial.loss-maker-history", "fact", ["sales", "CNI", "NFO"], 2, "Loss-making history and current revenue."),
      requirement("common.market-price-and-shares", "market", ["market-price", "diluted-shares"], 1, "Current market price and shares."),
    ],
    guards: [],
    implementation: implementation("src/engine/lossMakerValuation.ts", "computeLossMakerValuation", "reverseDCF", "wired", "Emitted inside the loss-maker bundle."),
    lifecycleNote: "Wired but market-implied; never count as intrinsic support.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.loss-maker-profitability-path",
    modelVersion: "legacy-unversioned",
    label: "Loss-maker profitability path",
    description: "Cash runway, growth, and margin-direction diagnostic for loss-making issuers.",
    inputContract: "loss-maker-valuation-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [requirement("industrial.loss-maker-history", "fact", ["sales", "CNI", "CFO", "NFO"], 2, "Loss-making, cash-burn, and revenue history.")],
    guards: [],
    implementation: implementation("src/engine/lossMakerValuation.ts", "computeLossMakerValuation", "profitabilityPath", "wired", "Emitted inside the pipeline loss-maker bundle."),
    lifecycleNote: "Operational diagnostic only; it does not publish a countable valuation.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.scenario-headline",
    modelVersion: "legacy-unversioned",
    label: "Industrial scenario headline",
    description: "Scenario-level center produced from underlying accrual and owner-earnings families.",
    inputContract: "industrial-scenario-values-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "aggregator",
    lifecycle: "production",
    independenceGroup: "aggregation",
    requirements: [requirement("industrial.scenario-model-results", "assumption", ["accrual-family-value", "owner-earnings-value"], 1, "At least one finite underlying scenario valuation.")],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/valuationCommandCenter/helpers.ts", "computeScenarioIntrinsicPerShare", null, "wired", "Collapses RI/ReOI before combining with owner earnings."),
    lifecycleNote: "Wired aggregator; its finite output is never a separately computed model.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.evidence-weighted-synthesis",
    modelVersion: "legacy-unversioned",
    label: "Evidence-weighted valuation synthesis",
    description: "Combines eligible evidence families into a guarded range and defensibility result.",
    inputContract: "valuation-evidence-synthesis-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "aggregator",
    lifecycle: "production",
    independenceGroup: "aggregation",
    requirements: [requirement("industrial.synthesis-contributions", "assumption", ["model-results", "evidence-ledger", "forecast-holdout"], 1, "Underlying model results and evidence-quality metadata.")],
    guards: [],
    implementation: implementation("src/engine/valuationEvidence/evidenceWeightedSynthesis.ts", "buildEvidenceWeightedSynthesis", null, "wired", "Constructed by the industrial command center."),
    lifecycleNote: "Wired aggregator, explicitly excluded from intrinsic and relative model counts.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.damodaran-capm-cross-check",
    modelVersion: "2026-01-data",
    label: "Damodaran CAPM cross-check",
    description: "Independent industry-beta cost-of-equity diagnostic used to challenge configured ke.",
    inputContract: "damodaran-capm-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "capital-cost-diagnostic",
    requirements: [requirement("industrial.company-type-beta", "market", ["company-type", "industry-beta", "risk-free-rate", "equity-risk-premium"], 1, "A mapped company type and dated CAPM inputs.")],
    guards: [],
    implementation: implementation("src/engine/valuation/damodaranCapm.ts", "capmKe", null, "wired", "Built by the industrial command center as a ke cross-check, not the authoritative cost resolver."),
    lifecycleNote: "Wired diagnostic; it does not constitute a valuation model or independent value observation.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.clean-surplus-check",
    modelVersion: "legacy-unversioned",
    label: "Clean-surplus diagnostic",
    description: "Tests whether changes in common equity reconcile to comprehensive income and owner transactions.",
    inputContract: "clean-surplus-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "accounting-quality",
    requirements: [requirement("industrial.clean-surplus-history", "fact", ["CSE", "comprehensive-income", "dividends", "net-stock-issuance"], 2, "Two aligned clean-surplus periods.")],
    guards: [],
    implementation: implementation("src/engine/valuation/cleanSurplus.ts", "checkCleanSurplus", null, "wired", "Executed by the command center and surfaced as an analytical-depth check."),
    lifecycleNote: "Wired diagnostic and model guard input; never a valuation count.",
    replacementModelId: null,
  }),
  define({
    modelId: "industrial.working-capital-gate",
    modelVersion: "legacy-unversioned",
    label: "Working-capital gate",
    description: "Cash-conversion-cycle diagnostic that guards forecasts against stretched working capital.",
    inputContract: "working-capital-gate-input-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [requirement("industrial.working-capital-history", "fact", ["sales", "COGS", "receivables", "inventory", "payables"], 2, "Two periods of working-capital drivers.")],
    guards: [],
    implementation: implementation("src/engine/valuation/workingCapitalGate.ts", "evaluateWorkingCapitalGate", null, "wired", "Executed by the command center as a quality and forecast guard."),
    lifecycleNote: "Wired diagnostic; it can guard a model but is not itself a model count.",
    replacementModelId: null,
  }),

  define({
    modelId: "fi.bank.justified-pb-gordon",
    modelVersion: "legacy-unversioned",
    label: "Bank justified P/B Gordon",
    description: "Book-value valuation from sustainable ROE, cost of equity, and terminal growth.",
    inputContract: "bank-valuation-input-v1",
    families: ["bank", "nbfc"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "fi-book-residual-income",
    requirements: [
      requirement("fi.positive-book-value", "fact", ["total-equity"], 1, "Positive latest book value."),
      requirement("fi.sustainable-roe", "fact", ["ROE", "total-equity", "PAT"], 3, "At least three positive ROE observations."),
      requirement("fi.equity-capital-cost", "assumption", ["ke", "terminal-growth"], 1, "Cost of equity and terminal growth."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/coreModels.ts", "justifiedPBGordon", null, "wired", "Computed by computeBankValuation for bank and NBFC runs."),
    lifecycleNote: "Wired; shares book/ROE evidence with FI residual-income lenses and therefore one independence group.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.bank.equity-residual-income",
    modelVersion: "legacy-unversioned",
    label: "Bank equity residual income",
    description: "Five-year equity residual-income forecast with ROE fade and a terminal value.",
    inputContract: "bank-valuation-input-v1",
    families: ["bank", "nbfc"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "fi-book-residual-income",
    requirements: [
      requirement("fi.book-earnings-history", "fact", ["total-equity", "PAT", "ROE"], 3, "At least three periods with positive book value and earnings observations."),
      requirement("fi.equity-capital-cost", "assumption", ["ke", "terminal-growth"], 1, "Cost of equity and terminal growth."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/coreModels.ts", "equityResidualIncome", null, "wired", "Computed by computeBankValuation."),
    lifecycleNote: "Wired but correlated with justified P/B through the same equity, ROE, ke, and growth evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.bank.sustainable-ddm",
    modelVersion: "legacy-unversioned",
    label: "Bank sustainable DDM",
    description: "Dividend model with payout-growth sustainability checks.",
    inputContract: "bank-valuation-input-v1",
    families: ["bank", "nbfc"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "fi-distribution",
    requirements: [
      requirement("fi.dividend-capacity", "fact", ["PAT", "total-equity", "ROE", "payout-ratio"], 1, "Positive earnings, book value, and a payout basis."),
      requirement("fi.equity-capital-cost", "assumption", ["ke", "terminal-growth"], 1, "Cost of equity and terminal growth."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, guard("distribution.sustainable-growth", "Terminal growth must be supported by retention times sustainable ROE."), FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/coreModels.ts", "sustainableDDM", null, "wired", "Computed by computeBankValuation; payout defaults remain visible when actual distribution data is missing."),
    lifecycleNote: "Wired distribution lens, though independence is strongest only when payout evidence is actually sourced rather than defaulted.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.insurance.embedded-value-vnb",
    modelVersion: "legacy-unversioned",
    label: "Insurance embedded value and VNB",
    description: "Insurance equity value from disclosed embedded value plus value of new business.",
    inputContract: "insurance-embedded-value-input-v1",
    families: ["insurance"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "actuarial-embedded-value",
    requirements: [
      requirement("insurance.embedded-value", "sidecar", ["embedded-value"], 1, "Disclosed embedded value; insurance valuation fails closed without it."),
      requirement("insurance.vnb", "sidecar", ["VNB"], 1, "Value of new business for the primary EV plus VNB method.", "enrichment"),
      requirement("insurance.ev-multiple", "assumption", ["VNB-multiple", "EV-multiple"], 1, "Explicit actuarial valuation multiple."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/coreModels.ts", "evBasedValuation", null, "wired", "computeBankValuation makes this primary for insurers and fails closed when EV is missing."),
    lifecycleNote: "Wired as the insurance-native primary currently available; sidecar provenance and period alignment remain required evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.nbfc.p-aum",
    modelVersion: "legacy-unversioned",
    label: "NBFC P/AUM",
    description: "AUM valuation using sustainable ROA and an explicit P/E-derived P/AUM multiple.",
    inputContract: "nbfc-valuation-input-v1",
    families: ["nbfc"],
    category: "relative",
    lifecycle: "production",
    independenceGroup: "fi-asset-market-multiple",
    requirements: [
      requirement("nbfc.aum", "sidecar", ["AUM"], 1, "Positive AUM from the quality sidecar."),
      requirement("nbfc.sustainable-roa", "fact", ["ROA"], 3, "At least three positive ROA observations."),
      requirement("nbfc.paum-multiple", "assumption", ["P-E-multiple"], 1, "The applied P/E-to-P/AUM multiple."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/nbfcLenses.ts", "pAumLens", null, "wired", "Computed only for NBFC subtype runs with AUM evidence."),
    lifecycleNote: "Wired relative/asset lens; its fixed multiple is an assumption, not independent market evidence unless sourced.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.nbfc.roa-leverage-residual-income",
    modelVersion: "legacy-unversioned",
    label: "NBFC ROA x leverage residual income",
    description: "Seven-year residual-income forecast decomposed into ROA and leverage paths.",
    inputContract: "nbfc-valuation-input-v1",
    families: ["nbfc"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "fi-book-residual-income",
    requirements: [
      requirement("nbfc.roa-leverage-history", "fact", ["total-equity", "PAT", "ROA", "leverage"], 3, "At least three usable NBFC periods."),
      requirement("fi.equity-capital-cost", "assumption", ["ke", "terminal-growth"], 1, "Cost of equity and terminal growth."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/nbfcLenses.ts", "roaLeverageRI", null, "wired", "Computed only for NBFC subtype runs."),
    lifecycleNote: "Wired but grouped with other book residual-income methods; a decomposition is not independent corroboration.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.median-triangulation",
    modelVersion: "legacy-unversioned",
    label: "FI median triangulation",
    description: "Median of finite bank/NBFC model outputs, or the EV primary for insurance.",
    inputContract: "fi-model-results-v1",
    families: FI_FAMILIES,
    category: "aggregator",
    lifecycle: "production",
    independenceGroup: "aggregation",
    requirements: [requirement("fi.computed-model-results", "assumption", ["model-results"], 1, "At least one finite applicable model result; insurance additionally requires EV." )],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/computeBankValuation.ts", "computeBankValuation", "triangulatedValue", "wired", "Legacy bundle aggregation; catalog helpers do not count it as a model."),
    lifecycleNote: "Wired aggregator, explicitly excluded from model counts and independent evidence groups.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.bank.scenario-bundle",
    modelVersion: "legacy-unversioned",
    label: "FI scenario bundle",
    description: "Stress/base/bull scenario cards derived from bank or NBFC valuation drivers.",
    inputContract: "fi-scenario-input-v1",
    families: ["bank", "nbfc"],
    category: "aggregator",
    lifecycle: "production",
    independenceGroup: "aggregation",
    requirements: [requirement("fi.scenario-drivers", "assumption", ["sustainable-ROE", "ke", "terminal-growth", "book-value"], 1, "Resolved scenario drivers." )],
    guards: [],
    implementation: implementation("src/engine/bankValuation/scenarios.ts", "buildBankScenarioBundle", null, "wired", "Computed by computeBankValuation."),
    lifecycleNote: "Scenario presentation/aggregation, not another valuation model.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.bank.relative-multiples",
    modelVersion: "legacy-unversioned",
    label: "Bank relative multiples",
    description: "Bank P/B, P/E, and price/NII relative-value bands.",
    inputContract: "bank-relative-multiples-v1",
    families: ["bank", "nbfc"],
    category: "relative",
    lifecycle: "experimental",
    independenceGroup: "peer-market",
    requirements: [
      requirement("fi.relative-history", "fact", ["total-equity", "PAT", "NII"], 2, "Bank historical fundamentals."),
      requirement("common.market-cap", "market", ["market-cap"], 1, "Current market capitalization."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/relativeValuation.ts", "computeBankMultiples", "impliedFairValueComposite", "not-wired", "The implementation and tests exist, but no production FI analysis or report calls it."),
    lifecycleNote: "Experimental until it is connected to the FI run and trust envelope with peer evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "fi.segment-sotp",
    modelVersion: "legacy-unversioned",
    label: "FI segment SOTP",
    description: "Proposed sum-of-parts bridge for lender subsidiaries or business segments.",
    inputContract: "fi-segment-sotp-v1",
    families: FI_FAMILIES,
    category: "intrinsic",
    lifecycle: "experimental",
    independenceGroup: "segment-sotp",
    requirements: [requirement("fi.segment-evidence", "segment", ["segment-earnings", "segment-book-value", "segment-capital"], 2, "At least two FI segments with native valuation drivers.")],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/bankValuation/sotp.ts", "buildBankSOTP", null, "not-wired", "The current bridge is explicitly a placeholder and always returns null."),
    lifecycleNote: "Experimental placeholder; a strategy/company label must never grant native SOTP computation credit.",
    replacementModelId: null,
  }),

  define({
    modelId: "sector.utility.rab-ddm",
    modelVersion: "1.0.0",
    label: "Utility regulated-asset-base DDM",
    description: "Allowed-return equity cash flow on a reconciled regulated rate base, CWIP, and regulatory deferrals.",
    inputContract: "utility-rab-case-v1",
    families: ["utility"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [
      requirement("utility.rate-base", "fact", ["regulated-rate-base", "CWIP", "regulatory-assets", "regulatory-liabilities"], 1, "Trace-backed regulated asset base and deferrals."),
      requirement("utility.tariff-return", "assumption", ["allowed-ROE", "terminal-growth", "cost-of-equity"], 1, "Allowed-return and terminal tariff economics."),
      requirement("utility.capital-structure", "fact", ["regulated-equity-weight", "net-debt", "diluted-shares"], 1, "Regulated capital structure and equity bridge."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sectorCases/calculators.ts", "executeSectorCase", "utility-rab", "partially-wired", "Typed computation is available through the sector-case registry; current audit runs do not infer it from utility routing."),
    lifecycleNote: "Production formula and eligibility contract; maturity credit still requires a typed eligible computed result from real source evidence.",
    replacementModelId: null,
  }),
  define({
    modelId: "sector.nbfc.funding-justified-pb",
    modelVersion: "1.0.0",
    label: "NBFC funding-adjusted justified P/B",
    description: "One-stage justified price-to-book from sustainable ROA and leverage, with funding-spread and regulatory-capital guards.",
    inputContract: "nbfc-funding-case-v1",
    families: ["nbfc"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "fi-book-residual-income",
    requirements: [
      requirement("nbfc.aum-roa", "sidecar", ["AUM", "sustainable-ROA", "leverage"], 1, "Reviewed AUM, through-cycle ROA, and leverage."),
      requirement("nbfc.funding-credit-cost", "sidecar", ["asset-yield", "cost-of-borrowing", "credit-cost"], 1, "Reviewed through-cycle funding economics."),
      requirement("nbfc.regulatory-capital", "sidecar", ["capital-adequacy", "minimum-capital", "capital-buffer"], 1, "Applicable regulatory minimum and approved buffer."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sectorCases/calculators.ts", "executeSectorCase", "nbfc-funding", "partially-wired", "Typed computation is available through the sector-case registry; current audit runs require an approved sidecar and explicit integration."),
    lifecycleNote: "Production formula and eligibility contract; it is distinct from the seven-year ROA/leverage residual-income catalog model.",
    replacementModelId: null,
  }),
  define({
    modelId: "sector.telecom.subscriber-fcff",
    modelVersion: "1.0.0",
    label: "Telecom subscriber/network FCFF",
    description: "Subscriber and ARPU revenue bridge to network FCFF after maintenance, spectrum, lease, and debt obligations.",
    inputContract: "telecom-network-case-v1",
    families: ["telecom"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [
      requirement("telecom.subscriber-arpu", "fact", ["subscribers", "ARPU", "annual-revenue"], 1, "Trace-backed subscribers, ARPU, and revenue."),
      requirement("telecom.network-cash-flow", "fact", ["EBITDA-margin", "maintenance-capex", "spectrum-renewal-capex"], 1, "Network cash conversion inputs."),
      requirement("telecom.spectrum-lease", "fact", ["spectrum-obligations", "lease-liabilities", "net-debt"], 1, "Complete enterprise-to-equity obligations bridge."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sectorCases/calculators.ts", "executeSectorCase", "telecom-network", "partially-wired", "Typed computation is available through the sector-case registry; telecom strategy routing alone produces no result."),
    lifecycleNote: "Production formula and fail-closed evidence contract; scorecard credit requires a finite typed result, not TELECOM_NATIVE text.",
    replacementModelId: null,
  }),
  define({
    modelId: "sector.cyclical.mid-cycle-fcff",
    modelVersion: "1.0.0",
    label: "Cyclical mid-cycle FCFF",
    description: "Normalized volume, price, cash cost, fixed cost, and sustaining-capex valuation.",
    inputContract: "cyclical-mid-cycle-case-v1",
    families: ["industrial"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [
      requirement("cyclical.volume-price-cost", "fact", ["normalized-volume", "mid-cycle-price", "cash-cost", "fixed-costs"], 1, "Source-backed through-cycle operating inputs."),
      requirement("cyclical.sustaining-capex", "fact", ["sustaining-capex", "cash-tax-rate"], 1, "Through-cycle cash conversion."),
      requirement("cyclical.net-debt", "fact", ["net-debt", "diluted-shares"], 1, "Current equity bridge."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sectorCases/calculators.ts", "executeSectorCase", "cyclical-mid-cycle", "partially-wired", "Typed mid-cycle computation exists; no credit is inferred from cyclical-v1 routing."),
    lifecycleNote: "Production formula and eligibility contract; audit integration must supply source-backed normalized inputs.",
    replacementModelId: null,
  }),
  define({
    modelId: "sector.retail.unit-economics-fcff",
    modelVersion: "1.0.0",
    label: "Retail mature-store unit economics FCFF",
    description: "Mature-store revenue and cash economics after central costs and maintenance capex.",
    inputContract: "retail-unit-economics-case-v1",
    families: ["industrial"],
    category: "intrinsic",
    lifecycle: "production",
    independenceGroup: "operational-driver",
    requirements: [
      requirement("retail.mature-store-cohort", "fact", ["mature-store-count", "revenue-per-store", "store-EBITDA-margin"], 1, "Mature-store cohort economics."),
      requirement("retail.central-costs-capex", "fact", ["central-costs", "maintenance-capex-per-store", "cash-tax-rate"], 1, "Central overhead and maintenance burden."),
      requirement("retail.net-debt", "fact", ["net-debt", "diluted-shares"], 1, "Current equity bridge."),
    ],
    guards: [TERMINAL_SPREAD_GUARD, POSITIVE_SHARE_GUARD, FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/sectorCases/calculators.ts", "executeSectorCase", "retail-unit-economics", "partially-wired", "Typed mature-store computation exists but is not inferred for every consumer company."),
    lifecycleNote: "Production formula and eligibility contract; applicability requires an explicit mature-store cohort case.",
    replacementModelId: null,
  }),

  define({
    modelId: "advanced.real-options-rd-pipeline",
    modelVersion: "legacy-unversioned",
    label: "R&D pipeline real options",
    description: "Black-Scholes option value for staged R&D or expansion assets.",
    inputContract: "rd-pipeline-options-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "experimental",
    independenceGroup: "optionality",
    requirements: [requirement("advanced.rd-pipeline-disclosures", "sidecar", ["project-PV", "development-cost", "time-to-decision", "volatility", "probability-of-success"], 1, "Asset-level option inputs from reviewed disclosures.")],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/analysisRun/legacyExecutor.ts", "executeLegacyAnalysisRun", "advancedModelExecutions", "wired", "Approved sidecars execute into immutable run evidence; an independently reviewed exact-target policy can replace one synthesis vote, and production admission re-derives its authority from durable workspace reviews."),
    lifecycleNote: "Implementation is wired but lifecycle remains experimental and excluded from model counts until real-issuer goldens, calibration, full lineage, and dual-review promotion evidence pass.",
    replacementModelId: null,
  }),
  define({
    modelId: "advanced.peer-data-sotp",
    modelVersion: "2026-01-data",
    label: "Peer-data SOTP",
    description: "Standalone sector-multiple SOTP using the advanced peer-multiple snapshot.",
    inputContract: "peer-data-sotp-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "intrinsic",
    lifecycle: "experimental",
    independenceGroup: "segment-sotp",
    requirements: [
      requirement("industrial.segment-evidence", "segment", ["segment-name", "segment-operating-profit", "segment-assets"], 2, "At least two segments."),
      requirement("advanced.peer-multiple-snapshot", "market", ["sector-peer-multiple"], 1, "Dated sector peer multiple snapshot."),
    ],
    guards: [FINITE_VALUE_GUARD],
    implementation: implementation("src/engine/valuation/sotpValuation.ts", "sotpValuation", null, "not-wired", "Advanced implementation is test-only and separate from the wired command-center SOTP."),
    lifecycleNote: "Experimental until one authoritative SOTP path is selected and wired with evidence lineage.",
    replacementModelId: null,
  }),
  define({
    modelId: "advanced.credit-spread-wacc",
    modelVersion: "2026-01-data",
    label: "Credit-spread-aware WACC",
    description: "Bottom-up debt cost and WACC from sovereign curve and issuer credit spread.",
    inputContract: "credit-spread-wacc-v1",
    families: ["cross-family"],
    category: "diagnostic",
    lifecycle: "experimental",
    independenceGroup: "capital-cost-diagnostic",
    requirements: [requirement("advanced.credit-rating-tenor", "market", ["issuer-rating", "debt-tenor", "tax-rate", "capital-weights"], 1, "Dated rating, tenor, tax, and capital structure evidence." )],
    guards: [],
    implementation: implementation("src/engine/valuation/creditSpreadWacc.ts", "buildWacc", null, "not-wired", "Pure functions and data snapshot exist; the authoritative kw resolver does not call them."),
    lifecycleNote: "Experimental diagnostic until selected by the cross-module capital-cost resolver.",
    replacementModelId: null,
  }),
  define({
    modelId: "advanced.esg-adjusted-ke",
    modelVersion: "legacy-unversioned",
    label: "ESG-adjusted cost of equity",
    description: "Optional basis-point sensitivity applied to cost of equity from an ESG score or bucket.",
    inputContract: "esg-ke-sensitivity-v1",
    families: ["cross-family"],
    category: "diagnostic",
    lifecycle: "experimental",
    independenceGroup: "capital-cost-diagnostic",
    requirements: [requirement("advanced.esg-score", "sidecar", ["ESG-score", "ESG-rating", "rating-as-of"], 1, "Dated ESG evidence and an approved adjustment policy." )],
    guards: [],
    implementation: implementation("src/engine/analysisRun/legacyExecutor.ts", "executeLegacyAnalysisRun", "advancedModelExecutions", "partially-wired", "Governed requests execute into immutable diagnostic evidence; the structural cost-of-equity resolver remains unchanged."),
    lifecycleNote: "Experimental sensitivity only; excluded from valuation-model breadth and production maturity.",
    replacementModelId: null,
  }),
  define({
    modelId: "advanced.fx-neutral-revenue",
    modelVersion: "legacy-unversioned",
    label: "FX-neutral revenue diagnostic",
    description: "Separates reported revenue growth from currency-translation effects.",
    inputContract: "fx-neutral-revenue-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "experimental",
    independenceGroup: "operational-driver",
    requirements: [requirement("advanced.fx-revenue-history", "sidecar", ["reported-revenue", "average-FX-rate", "closing-FX-rate", "foreign-currency-mix"], 2, "Two periods of currency exposure data." )],
    guards: [],
    implementation: implementation("src/engine/analysisRun/legacyExecutor.ts", "executeLegacyAnalysisRun", "advancedModelExecutions", "partially-wired", "Governed requests execute into immutable diagnostic evidence; forecast assumptions do not yet consume the output."),
    lifecycleNote: "Experimental diagnostic until source ingestion and forecast integration are implemented.",
    replacementModelId: null,
  }),
  define({
    modelId: "advanced.lease-capitalization",
    modelVersion: "legacy-unversioned",
    label: "Lease capitalization diagnostic",
    description: "Capitalizes operating leases and tests ROU/liability self-consistency.",
    inputContract: "lease-adjustment-v1",
    families: INDUSTRIAL_FAMILIES,
    category: "diagnostic",
    lifecycle: "experimental",
    independenceGroup: "accounting-adjustment",
    requirements: [requirement("advanced.lease-disclosures", "sidecar", ["annual-rent", "ROU-asset", "lease-liability", "lease-interest", "ROU-depreciation"], 1, "Lease disclosure facts and accounting-regime context." )],
    guards: [],
    implementation: implementation("src/engine/analysisRun/legacyExecutor.ts", "executeLegacyAnalysisRun", "advancedModelExecutions", "partially-wired", "Governed requests execute into immutable diagnostic evidence; recast and valuation do not consume the adjustment."),
    lifecycleNote: "Experimental diagnostic until the canonical recast prevents double counting and validates the adjustment end to end.",
    replacementModelId: null,
  }),
];

export const CURRENT_MODEL_DEFINITIONS: readonly ValuationModelDefinition[] = Object.freeze(
  [...CURRENT_MODEL_DEFINITIONS_MUTABLE],
);

export const CURRENT_MODEL_REGISTRY = ValuationModelRegistry.create(
  CURRENT_MODEL_CATALOG_VERSION,
  CURRENT_MODEL_DEFINITIONS,
);
