#!/usr/bin/env tsx
/**
 * tie-out.ts — compare every as-filed record under data/filings/ with the
 * Capitaline dataset the app analyses.
 *
 *   npx tsx scripts/filings/tie-out.ts
 *
 * Writes data/filings/tie-out.json and docs/generated/source-tieout.md.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCapitalineZip } from "../../src/engine/capitalineParser";
import { processCompanyDataFull } from "../../src/engine/pipeline";
import { DEFAULT_CONFIG } from "../../src/engine/types";
import { TIE_OUT_FIELDS, tieOutAsFiled, type AsFiledHeadlineRecord, type TieOutRow } from "../../src/engine/filings";

const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)), "../..");
const FILINGS = join(ROOT, "data", "filings");
const registry: { folder: string; ticker: string; type: string }[] =
  JSON.parse(readFileSync(join(ROOT, "public", "data", "companies", "registry.json"), "utf-8"));

const results: { symbol: string; rows: TieOutRow[]; firstFiling: string | null }[] = [];
for (const symbol of readdirSync(FILINGS).filter((d) => existsSync(join(FILINGS, d, "as-filed.json"))).sort()) {
  const company = registry.find((c) => c.ticker === symbol);
  if (!company) continue;
  const { records } = JSON.parse(readFileSync(join(FILINGS, symbol, "as-filed.json"), "utf8")) as { records: AsFiledHeadlineRecord[] };
  const buf = readFileSync(join(ROOT, "public", "data", "companies", company.folder, `${company.folder}.zip`));
  const parsed = await parseCapitalineZip(new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength), { companyId: company.folder });
  const periods = processCompanyDataFull(parsed.periods, { ...DEFAULT_CONFIG, company_type: company.type as typeof DEFAULT_CONFIG.company_type }).periods;
  results.push({ symbol, rows: tieOutAsFiled(records, periods), firstFiling: records[0]?.filingDate ?? null });
  console.log(`${symbol}: ${results.at(-1)!.rows.length} comparisons`);
}

writeFileSync(join(FILINGS, "tie-out.json"), JSON.stringify(results, null, 1) + "\n");

const all = results.flatMap((r) => r.rows.map((row) => ({ ...row, symbol: r.symbol })));
const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const fieldTable = TIE_OUT_FIELDS.map((field) => {
  const rows = all.filter((r) => r.field === field);
  const count = (status: string) => rows.filter((r) => r.status === status).length;
  const median = rows.length ? [...rows.map((r) => Math.abs(r.relativeDifference))].sort((a, b) => a - b)[Math.floor(rows.length / 2)]! : 0;
  return `| ${field} | ${rows.length} | ${count("match")} | ${count("minor")} | ${count("mismatch")} | ${count("filing-inconsistent")} | ${pct(median)} |`;
}).join("\n");
const worst = [...all].filter((r) => r.status === "mismatch").sort((a, b) => Math.abs(b.relativeDifference) - Math.abs(a.relativeDifference)).slice(0, 25);

writeFileSync(join(ROOT, "docs", "generated", "source-tieout.md"), `# Source tie-out: Capitaline vs as-filed XBRL

Generated by \`scripts/filings/tie-out.ts\`. Do not edit by hand.

Each company's consolidated annual results as **first filed** on NSE (XBRL, fetched by \`scripts/filings/fetch-nse-annual.ts\`) against the Capitaline figure the app analyses for the same year-end. Capitaline serves the latest (possibly restated) figures, so a difference is a mapping error, a restatement, or a definitional mismatch. Match ≤ 0.5%, minor ≤ 2%. **Filing inconsistent** means the as-filed figure contradicts its own filing (e.g. PAT above 1.5× PBT), so it cannot arbitrate — Asian Paints' FY22 XBRL reports PAT of ₹9,167 Cr against PBT of ₹4,156 Cr, and Capitaline's ₹3,085 Cr is right. As-filed is a source to reconcile against, not an oracle.

${results.length} companies, ${all.length} comparisons.

| Field | Compared | Match | Minor | Mismatch | Filing inconsistent | Median |difference| |
|---|---|---|---|---|---|---|
${fieldTable}

## Largest mismatches

Showing ${worst.length} of ${all.filter((r) => r.status === "mismatch").length} mismatches, largest first.

| Company | Year-end | Field | As filed (₹ Cr) | Capitaline (₹ Cr) | Difference |
|---|---|---|---|---|---|
${worst.map((r) => `| ${r.symbol} | ${r.fiscalYearEnd} | ${r.field} | ${r.asFiled.toFixed(0)} | ${r.capitaline.toFixed(0)} | ${pct(r.relativeDifference)} |`).join("\n")}
`);
console.log(`\n${all.length} comparisons across ${results.length} companies.`);
